/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Akinain(props) {
  const { nodes, materials } = useGLTF("/akinain-draco.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["36days_b001_mesh"].geometry}
        material={materials["Plastic_Polycarbonate_#1"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["36days_b002_mesh002"].geometry}
        material={materials["Plastic_Polycarbonate_#1"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["36days_b004_mesh004"].geometry}
        material={materials["Plastic_Polycarbonate_#1"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["3M_6200001_Mesh002_1"].geometry}
          material={materials["Material_#2_Slot_#1"]}
        />
        <mesh
          geometry={nodes["3M_6200001_Mesh002_2"].geometry}
          material={materials["3M_6200_RUBBER"]}
        />
        <mesh
          geometry={nodes["3M_6200001_Mesh002_3"].geometry}
          material={materials["3M_6200_BUCKLE"]}
        />
        <mesh
          geometry={nodes["3M_6200001_Mesh002_4"].geometry}
          material={materials["3M_6200_PLASTIC_GREY"]}
        />
        <mesh
          geometry={nodes["3M_6200001_Mesh002_5"].geometry}
          material={materials["3M_FILTER_SEAL"]}
        />
        <mesh
          geometry={nodes["3M_6200001_Mesh002_6"].geometry}
          material={materials["3M_6200_ELASTIC"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["3M_6200_Mesh_1"].geometry}
          material={materials["Material_#2_Slot_#1"]}
        />
        <mesh geometry={nodes["3M_6200_Mesh_2"].geometry} material={materials["3M_6200_RUBBER"]} />
        <mesh geometry={nodes["3M_6200_Mesh_3"].geometry} material={materials["3M_6200_BUCKLE"]} />
        <mesh
          geometry={nodes["3M_6200_Mesh_4"].geometry}
          material={materials["3M_6200_PLASTIC_GREY"]}
        />
        <mesh geometry={nodes["3M_6200_Mesh_5"].geometry} material={materials["3M_FILTER_SEAL"]} />
        <mesh geometry={nodes["3M_6200_Mesh_6"].geometry} material={materials["3M_6200_ELASTIC"]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes["3M_FILTER001_Mesh003_1"].geometry} material={materials["(null)"]} />
        <mesh
          geometry={nodes["3M_FILTER001_Mesh003_2"].geometry}
          material={materials["3M_FILTER_SEAL"]}
        />
        <mesh
          geometry={nodes["3M_FILTER001_Mesh003_3"].geometry}
          material={materials["3M_FILTER_GREY"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["3M_FILTER_Mesh001_1"].geometry}
          material={materials["3M_FILTER_FABRIC"]}
        />
        <mesh
          geometry={nodes["3M_FILTER_Mesh001_2"].geometry}
          material={materials["3M_FILTER_SEAL"]}
        />
        <mesh
          geometry={nodes["3M_FILTER_Mesh001_3"].geometry}
          material={materials["3M_FILTER_GREY"]}
        />
      </group>
      <mesh
        geometry={nodes.belt_b001_mesh001.geometry}
        material={materials["Cloth_Weave_Black_1mm_#1"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.belt_b002_mesh003.geometry}
        material={materials["Cloth_Weave_Black_1mm_#1"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.belt_b003_mesh005.geometry}
        material={materials["Cloth_Weave_Black_1mm_#1"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1001.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1002.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1003.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1004.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1005.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1006.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1007.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1008.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1009.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1010.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1011.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1012.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1013.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1014.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1015.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1016.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1017.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1018.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1019.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1020.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1021.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1022.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1023.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1024.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1025.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1026.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1027.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1028.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1029.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1030.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1031.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1032.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1033.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1034.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1035.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1036.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1037.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1038.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1039.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1040.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1041.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1042.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1043.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1044.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1045.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1046.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1047.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1048.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1049.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1050.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1051.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1052.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1053.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1054.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1055.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1056.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1057.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1058.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1059.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1060.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1061.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1062.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1063.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1064.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1065.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1066.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1067.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1068.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1069.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1070.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1071.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1072.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1073.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1074.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1075.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1076.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1077.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1078.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1079.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1080.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1081.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1082.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1083.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1084.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1085.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1086.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1087.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1088.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1089.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1090.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1091.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1092.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1093.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1094.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1095.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1096.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1097.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1098.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1099.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1100.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1101.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1102.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1103.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1104.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1105.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1106.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1107.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1108.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1109.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1110.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1111.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1112.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1113.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1114.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1115.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1116.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1117.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1118.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1119.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1120.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1121.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1122.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1123.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1124.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1125.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1126.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1127.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1128.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1129.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1130.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1131.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1132.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1133.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1134.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1135.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1136.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1137.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1138.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1139.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1140.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1141.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1142.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1143.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1144.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1145.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1146.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1147.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1148.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1149.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1150.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1151.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1152.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1153.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1154.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1155.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1156.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1157.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1158.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1159.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1160.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1161.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1162.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1163.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1164.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1165.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1166.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1167.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1168.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1169.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1170.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1171.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1172.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1173.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1174.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1175.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1176.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1177.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1178.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1179.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1180.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1181.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1182.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1183.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1184.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1185.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1186.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1187.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1188.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1189.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1190.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1191.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1192.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1193.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1194.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1195.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1196.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1197.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1198.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1199.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1200.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1201.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1202.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1203.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1204.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1205.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1206.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1207.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1208.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1209.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1210.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1211.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1212.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1213.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1214.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1215.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1216.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1217.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1218.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1219.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1220.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1221.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1222.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1223.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1224.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1225.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1226.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1227.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1228.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1229.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1230.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1231.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1232.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1233.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1234.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1235.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1236.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1237.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1238.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1239.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1240.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1241.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1242.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1243.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1244.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1245.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1246.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1247.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1248.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1249.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1250.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1251.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1252.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1253.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1254.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1255.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1256.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1257.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1258.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1259.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1260.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1261.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1262.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1263.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1264.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1265.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1266.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1267.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1268.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1269.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1270.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1271.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1272.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1273.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1274.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1275.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1276.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1277.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1278.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1279.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1280.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1281.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1282.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1283.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1284.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1285.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1286.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1287.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1288.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1289.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1290.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1291.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1292.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1293.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1294.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1295.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1296.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1297.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1298.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1299.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1300.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1301.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1302.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1303.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1304.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1305.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1306.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1307.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1308.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1309.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1310.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1311.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1312.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1313.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1314.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1315.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1316.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1317.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1318.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1319.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1320.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1321.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1322.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1323.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1324.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1325.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1326.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1327.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1328.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1329.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1330.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1331.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1332.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1333.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1334.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1335.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1336.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1337.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1338.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1339.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1340.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1341.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1342.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1343.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1344.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1345.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1346.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1347.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_1348.geometry}
        material={materials.Material_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/akinain-draco.gltf");
