/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Dipak(props) {
  const { nodes, materials } = useGLTF("/dipak-draco.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.개체_1.geometry} material={materials["재질_2.001"]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_1001.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_1002.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_30.geometry}
          material={materials["Material.010"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_30001.geometry}
          material={materials["Material.010"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_31.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_31001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_108.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_108001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_125.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_125001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_3.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_3001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_82.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_82001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_95.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_95001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_10.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_10001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_100.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_100001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_103.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_103001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_107.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_107001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_11.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_11001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_111.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_111001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_112.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_112001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_113.geometry}
          material={materials["Material.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_113001.geometry}
          material={materials["Material.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_116.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_116001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_117.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_117001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_12.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_12001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_120.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_120001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_121.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_121001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_122.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_122001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_126.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_126001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_13.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_13001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_34.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_34001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_4.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_4001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_45.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_45001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_5.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_5001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_56.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_56001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_6.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_6001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_7.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_7001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_77.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_77001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_8.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_8001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_81.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_81001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_85.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_85001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_86.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_86001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_87.geometry}
          material={materials["Material.009"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_87001.geometry}
          material={materials["Material.009"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_9.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_9001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_90.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_90001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_94.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_94001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_98.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_98001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_99.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_99001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_110.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_110001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_123.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_123001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_14.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_14001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_15.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_15001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_16.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_16001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_17.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_17001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_18.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_18001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_19.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_19001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_20.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_20001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_21.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_21001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_22.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_22001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_23.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_23001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_24.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_24001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_25.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_25001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_26.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_26001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_27.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_27001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_28.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_28001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_29.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_29001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_32.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_32001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_33.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_33001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_35.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_35001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_36.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_36001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_37.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_37001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_38.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_38001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_39.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_39001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_40.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_40001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_41.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_41001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_42.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_42001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_43.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_43001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_46.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_46001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_47.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_47001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_48.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_48001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_49.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_49001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_50.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_50001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_51.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_51001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_52.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_52001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_53.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_53001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_54.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_54001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_57.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_57001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_58.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_58001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_59.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_59001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_60.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_60001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_61.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_61001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_62.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_62001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_63.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_63001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_64.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_64001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_65.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_65001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_68.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_68001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_69.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_69001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_70.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_70001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_71.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_71001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_72.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_72001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_73.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_73001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_74.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_74001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_75.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_75001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_76.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_76001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_84.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_84001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_97.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_97001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_44.geometry}
          material={materials["Material.008"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_44001.geometry}
          material={materials["Material.008"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_55.geometry}
          material={materials["Material.008"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_55001.geometry}
          material={materials["Material.008"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_66.geometry}
          material={materials["Material.008"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_66001.geometry}
          material={materials["Material.008"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_67.geometry}
          material={materials["Material.008"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_67001.geometry}
          material={materials["Material.008"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_104.geometry}
          material={materials["Material.010"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_104001.geometry}
          material={materials["Material.010"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_105.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_105001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_106.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_106001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_127.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_127001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_128.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_128001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_129.geometry}
          material={materials["Material.010"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_129001.geometry}
          material={materials["Material.010"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_78.geometry}
          material={materials["Material.010"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_78001.geometry}
          material={materials["Material.010"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_79.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_79001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_80.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_80001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_91.geometry}
          material={materials["Material.010"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_91001.geometry}
          material={materials["Material.010"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_92.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_92001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_93.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_93001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_109.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_109001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_124.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_124001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_83.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_83001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_96.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_96001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          geometry={nodes.개체_101.geometry}
          material={materials["Material.006"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_101001.geometry}
          material={materials["Material.006"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_102.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_102001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_114.geometry}
          material={materials["Material.006"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_114001.geometry}
          material={materials["Material.006"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_115.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_115001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_118.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_118001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_119.geometry}
          material={materials["Material.006"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_119001.geometry}
          material={materials["Material.006"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_88.geometry}
          material={materials["Material.006"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_88001.geometry}
          material={materials["Material.006"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
        <mesh
          geometry={nodes.개체_89.geometry}
          material={materials["재질_2.004"]}
          position={[-99.76, -653.87, 3.66]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={0.63}
        />
        <mesh
          geometry={nodes.개체_89001.geometry}
          material={materials["재질_2.004"]}
          position={[168.2, -2304.03, -166.14]}
          rotation={[-1.22, -0.66, 2.02]}
          scale={1.86}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
        <mesh
          geometry={nodes.개체_1003.geometry}
          material={materials["재질_2.005"]}
          position={[-180.84, -493.51, 104.58]}
          scale={5.53}
        />
        <mesh
          geometry={nodes.개체_1004.geometry}
          material={materials["재질_2.005"]}
          position={[-90.27, -508.99, 80.07]}
          scale={8.09}
        />
        <mesh
          geometry={nodes.개체_1005.geometry}
          material={materials["재질_2.005"]}
          position={[-147.74, -584.31, -10.31]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1006.geometry}
          material={materials["재질_2.005"]}
          position={[-147.74, -599.9, -10.31]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1007.geometry}
          material={materials["재질_2.005"]}
          position={[-147.74, -615.39, -10.31]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1008.geometry}
          material={materials["재질_2.005"]}
          position={[-147.74, -630.97, -10.31]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1009.geometry}
          material={materials["재질_2.005"]}
          position={[-165.94, -646.97, -7.85]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1010.geometry}
          material={materials["재질_2.005"]}
          position={[-165.94, -662.55, -7.85]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1011.geometry}
          material={materials["재질_2.005"]}
          position={[-165.94, -682.56, -7.85]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1012.geometry}
          material={materials["재질_2.005"]}
          position={[-165.94, -698.15, -7.85]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1013.geometry}
          material={materials["재질_2.005"]}
          position={[2.65, -672.98, 109.55]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1014.geometry}
          material={materials["재질_2.005"]}
          position={[2.65, -688.57, 109.55]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1015.geometry}
          material={materials["재질_2.005"]}
          position={[2.65, -704.06, 109.55]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1016.geometry}
          material={materials["재질_2.005"]}
          position={[2.65, -719.65, 109.55]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1017.geometry}
          material={materials["재질_2.005"]}
          position={[-15.55, -735.64, 112.01]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1018.geometry}
          material={materials["재질_2.005"]}
          position={[-15.55, -751.23, 112.01]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1019.geometry}
          material={materials["재질_2.005"]}
          position={[-15.55, -771.23, 112.01]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1020.geometry}
          material={materials["재질_2.005"]}
          position={[-15.55, -786.82, 112.01]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1021.geometry}
          material={materials["재질_2.005"]}
          position={[-86.1, -916.13, 129.3]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1022.geometry}
          material={materials["재질_2.005"]}
          position={[-86.1, -931.71, 129.3]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1023.geometry}
          material={materials["재질_2.005"]}
          position={[-86.1, -947.21, 129.3]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1024.geometry}
          material={materials["재질_2.005"]}
          position={[-86.1, -962.79, 129.3]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1025.geometry}
          material={materials["재질_2.005"]}
          position={[-86.91, -978.78, 131.76]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1026.geometry}
          material={materials["재질_2.005"]}
          position={[-86.91, -994.37, 131.76]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1027.geometry}
          material={materials["재질_2.005"]}
          position={[-86.91, -1014.38, 131.76]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1028.geometry}
          material={materials["재질_2.005"]}
          position={[-86.91, -1029.97, 131.76]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1029.geometry}
          material={materials["재질_2.005"]}
          position={[139.22, -1625.66, 55.25]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1030.geometry}
          material={materials["재질_2.005"]}
          position={[139.22, -1641.25, 55.25]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1031.geometry}
          material={materials["재질_2.005"]}
          position={[139.22, -1656.74, 55.25]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1032.geometry}
          material={materials["재질_2.005"]}
          position={[139.22, -1672.33, 55.25]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1033.geometry}
          material={materials["재질_2.005"]}
          position={[138.4, -1688.32, 57.7]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1034.geometry}
          material={materials["재질_2.005"]}
          position={[138.4, -1703.91, 57.7]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1035.geometry}
          material={materials["재질_2.005"]}
          position={[138.4, -1723.92, 57.7]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1036.geometry}
          material={materials["재질_2.005"]}
          position={[138.4, -1739.5, 57.7]}
          scale={3.15}
        />
        <mesh
          geometry={nodes.개체_1037.geometry}
          material={materials["재질_2.005"]}
          position={[-213.37, -1599.23, 6.21]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1038.geometry}
          material={materials["재질_2.005"]}
          position={[-213.37, -1622.2, 6.21]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1039.geometry}
          material={materials["재질_2.005"]}
          position={[-213.37, -1645.03, 6.21]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1040.geometry}
          material={materials["재질_2.005"]}
          position={[-213.37, -1668.01, 6.21]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1041.geometry}
          material={materials["재질_2.005"]}
          position={[-214.58, -1691.57, 9.83]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1042.geometry}
          material={materials["재질_2.005"]}
          position={[-214.58, -1714.54, 9.83]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1043.geometry}
          material={materials["재질_2.005"]}
          position={[-214.58, -1744.03, 9.83]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1044.geometry}
          material={materials["재질_2.005"]}
          position={[-214.58, -1767, 9.83]}
          scale={4.64}
        />
        <mesh
          geometry={nodes.개체_1045.geometry}
          material={materials["재질_2.005"]}
          position={[-86.64, -1840.85, 67.6]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1046.geometry}
          material={materials["재질_2.005"]}
          position={[-86.64, -1872.24, 67.6]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1047.geometry}
          material={materials["재질_2.005"]}
          position={[-86.64, -1903.43, 67.6]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1048.geometry}
          material={materials["재질_2.005"]}
          position={[-86.64, -1934.82, 67.6]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1049.geometry}
          material={materials["재질_2.005"]}
          position={[-88.28, -1967.02, 72.55]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1050.geometry}
          material={materials["재질_2.005"]}
          position={[-88.28, -1998.4, 72.55]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1051.geometry}
          material={materials["재질_2.005"]}
          position={[-88.28, -2038.69, 72.55]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1052.geometry}
          material={materials["재질_2.005"]}
          position={[-88.28, -2070.08, 72.55]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1053.geometry}
          material={materials["재질_2.005"]}
          position={[501.32, -2349.44, -55.18]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1054.geometry}
          material={materials["재질_2.005"]}
          position={[501.32, -2380.83, -55.18]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1055.geometry}
          material={materials["재질_2.005"]}
          position={[501.32, -2412.02, -55.18]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1056.geometry}
          material={materials["재질_2.005"]}
          position={[501.32, -2443.41, -55.18]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1057.geometry}
          material={materials["재질_2.005"]}
          position={[499.68, -2475.61, -50.24]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1058.geometry}
          material={materials["재질_2.005"]}
          position={[499.68, -2507, -50.24]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1059.geometry}
          material={materials["재질_2.005"]}
          position={[499.68, -2547.28, -50.24]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1060.geometry}
          material={materials["재질_2.005"]}
          position={[499.68, -2578.67, -50.24]}
          scale={6.34}
        />
        <mesh
          geometry={nodes.개체_1061.geometry}
          material={materials["재질_2.005"]}
          position={[-180.84, -531.71, 104.58]}
          scale={5.53}
        />
        <mesh
          geometry={nodes.개체_1062.geometry}
          material={materials["재질_2.005"]}
          position={[-180.84, -576.94, 104.58]}
          scale={5.53}
        />
      </group>
      <mesh
        geometry={nodes.Box148001.geometry}
        material={materials.Standardmaterial_3}
        position={[-3870.05, -153.88, 2010.22]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.41}
      />
      <group position={[-3870.35, -132.52, 1969.18]} rotation={[0, 0, -Math.PI / 2]} scale={0.26}>
        <mesh geometry={nodes.Mesh481.geometry} material={materials.Standardmaterial_3} />
        <mesh geometry={nodes.Mesh481_1.geometry} material={materials["Material #25"]} />
      </group>
      <group position={[-3870.35, -132.52, 1993.21]} rotation={[0, 0, -Math.PI / 2]} scale={0.26}>
        <mesh geometry={nodes.Mesh482.geometry} material={materials.Standardmaterial_3} />
        <mesh geometry={nodes.Mesh482_1.geometry} material={materials["Material #25"]} />
      </group>
      <mesh
        geometry={nodes.Plane004001.geometry}
        material={materials.Standardmaterial_3}
        position={[-3870.35, -132.52, 1982.35]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.26}
      />
      <mesh
        geometry={nodes.Mesher.geometry}
        material={materials["Default OBJ"]}
        position={[12.42, -11.2, -74.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.52}
      />
      <mesh
        geometry={nodes.Mesher001.geometry}
        material={materials["Default OBJ"]}
        position={[-25.33, -13.27, -68.18]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={22.66}
      />
      <mesh
        geometry={nodes.Mesher003.geometry}
        material={materials["Default OBJ"]}
        position={[29.6, -5.01, -94.51]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={11.89}
      />
      <mesh
        geometry={nodes.Mesher005.geometry}
        material={materials["Default OBJ"]}
        position={[-25.52, 5.06, -270.73]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.03}
      />
      <mesh
        geometry={nodes.Mesher006.geometry}
        material={materials["Default OBJ"]}
        position={[10.06, -20.41, -270.39]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.03}
      />
    </group>
  );
}

useGLTF.preload("/dipak-draco.gltf");
