/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Sajana2(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/sajana2.gltf");
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera002" position={[0, 0, -0.16]} rotation={[Math.PI / 2, 0, 0]} />
        <group
          name="rubber"
          position={[0.56, -0.45, -7.23]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_16"
            geometry={nodes.Object_16.geometry}
            material={materials["Material_2.002"]}
            position={[-6.41, -1666.68, 30.77]}
          />
          <mesh
            name="Object_16002"
            geometry={nodes.Object_16002.geometry}
            material={materials["Material_2.002"]}
            position={[-870.08, -7494.63, 279.33]}
          />
          <mesh
            name="Object_16006"
            geometry={nodes.Object_16006.geometry}
            material={materials["Material_2.002"]}
            position={[66.86, -9037.75, -223.79]}
          />
          <mesh
            name="Object_16007"
            geometry={nodes.Object_16007.geometry}
            material={materials["Material_2.002"]}
            position={[532.74, -12885.45, 336.66]}
          />
          <mesh
            name="Object_16008"
            geometry={nodes.Object_16008.geometry}
            material={materials["Material_2.002"]}
            position={[-148.46, -11808.4, -16.5]}
          />
          <mesh
            name="Object_16009"
            geometry={nodes.Object_16009.geometry}
            material={materials["Material_2.002"]}
            position={[-1686.83, -11225.68, -971.26]}
          />
        </group>
        <group
          name="rubber001"
          position={[1.69, -0.3, -19.99]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_16001"
            geometry={nodes.Object_16001.geometry}
            material={materials["Material_2.002"]}
            position={[-927.08, -1290.13, -271.88]}
          />
          <mesh
            name="Object_16003"
            geometry={nodes.Object_16003.geometry}
            material={materials["Material_2.002"]}
            position={[-1790.75, -7118.08, -23.32]}
          />
          <mesh
            name="Object_16004"
            geometry={nodes.Object_16004.geometry}
            material={materials["Material_2.002"]}
            position={[464.33, -7389.74, -818.48]}
          />
        </group>
        <group
          name="aluminum002"
          position={[-2.8, -0.93, -15.39]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_6"
            geometry={nodes.Object_6.geometry}
            material={materials["Material_2.003"]}
            position={[-740.46, -2999.46, -85.31]}
          />
          <mesh
            name="Object_6001"
            geometry={nodes.Object_6001.geometry}
            material={materials["Material_2.003"]}
            position={[0, -2238.01, -221.47]}
          />
          <mesh
            name="Object_6002"
            geometry={nodes.Object_6002.geometry}
            material={materials["Material_2.003"]}
            position={[-1405.5, -7487.07, 106.08]}
          />
          <mesh
            name="Object_6003"
            geometry={nodes.Object_6003.geometry}
            material={materials["Material_2.003"]}
            position={[-665.04, -6725.62, -30.08]}
          />
          <mesh
            name="Object_6004"
            geometry={nodes.Object_6004.geometry}
            material={materials["Material_2.003"]}
            position={[499.16, -7815.18, 118.51]}
          />
          <mesh
            name="Object_6005"
            geometry={nodes.Object_6005.geometry}
            material={materials["Material_2.003"]}
            position={[761.16, -4000.96, -105.44]}
          />
        </group>
        <group
          name="aluminum003"
          position={[-0.67, -1.74, -27.28]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1"
            geometry={nodes.Object_1.geometry}
            material={materials["Material_2.004"]}
            position={[508.46, 223.77, 99.56]}
          />
          <mesh
            name="Object_1006"
            geometry={nodes.Object_1006.geometry}
            material={materials["Material_2.004"]}
            position={[-221.65, -4702.98, 309.69]}
          />
          <mesh
            name="Object_1014"
            geometry={nodes.Object_1014.geometry}
            material={materials["Material_2.004"]}
            position={[-117.02, -3648.55, 343.72]}
          />
        </group>
        <group
          name="black003"
          position={[-0.67, -1.74, -27.28]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3"
            geometry={nodes.Object_3.geometry}
            material={materials["Material_2.004"]}
            position={[309.55, 218.28, 80.23]}
          />
          <mesh
            name="Object_3003"
            geometry={nodes.Object_3003.geometry}
            material={materials["Material_2.004"]}
            position={[-420.57, -4708.47, 290.36]}
          />
          <mesh
            name="Object_3011"
            geometry={nodes.Object_3011.geometry}
            material={materials["Material_2.004"]}
            position={[-315.94, -3654.04, 324.39]}
          />
        </group>
        <group
          name="aluminum004"
          position={[-0.67, -1.74, -42.96]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1001"
            geometry={nodes.Object_1001.geometry}
            material={materials["Material_2.004"]}
          />
        </group>
        <group
          name="black004"
          position={[-0.67, -1.74, -42.96]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3001"
            geometry={nodes.Object_3001.geometry}
            material={materials["Material_2.004"]}
          />
        </group>
        <group
          name="aluminum005"
          position={[-5.23, -2.89, -54.7]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1002"
            geometry={nodes.Object_1002.geometry}
            material={materials["Material_2.004"]}
          />
          <mesh
            name="Object_1008"
            geometry={nodes.Object_1008.geometry}
            material={materials["Material_2.004"]}
            position={[-393.2, -4926.75, 31.04]}
          />
        </group>
        <group
          name="black005"
          position={[-5.23, -2.89, -54.7]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3002"
            geometry={nodes.Object_3002.geometry}
            material={materials["Material_2.004"]}
          />
          <mesh
            name="Object_3005"
            geometry={nodes.Object_3005.geometry}
            material={materials["Material_2.004"]}
            position={[-393.2, -4926.75, 31.04]}
          />
        </group>
        <group
          name="레이어_08"
          position={[9.49, 10.7, -28.15]}
          rotation={[Math.PI / 2, 0, -0.23]}
          scale={0.02}
        >
          <group
            name="개체_281001"
            position={[-473.37, -292.45, 534.25]}
            rotation={[1.39, -0.25, -1.34]}
            scale={0.65}
          >
            <mesh
              name="개체_281001_1"
              geometry={nodes.개체_281001_1.geometry}
              material={materials["Material6.002"]}
            />
            <mesh
              name="개체_281001_2"
              geometry={nodes.개체_281001_2.geometry}
              material={materials["Material29.002"]}
            />
            <mesh
              name="개체_281001_3"
              geometry={nodes.개체_281001_3.geometry}
              material={materials["재질_2.003"]}
            />
            <mesh
              name="개체_281001_4"
              geometry={nodes.개체_281001_4.geometry}
              material={materials["Material_2.006"]}
            />
            <mesh
              name="개체_281001_5"
              geometry={nodes.개체_281001_5.geometry}
              material={materials["Material17.002"]}
            />
            <mesh
              name="개체_281001_6"
              geometry={nodes.개체_281001_6.geometry}
              material={materials["default"]}
            />
            <mesh
              name="개체_281001_7"
              geometry={nodes.개체_281001_7.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              name="개체_281001_8"
              geometry={nodes.개체_281001_8.geometry}
              material={materials["Material4.002"]}
            />
            <mesh
              name="개체_281001_9"
              geometry={nodes.개체_281001_9.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              name="개체_281001_10"
              geometry={nodes.개체_281001_10.geometry}
              material={materials["Material3.002"]}
            />
          </group>
          <group
            name="개체_281002"
            position={[-94.67, -1013.53, 571.89]}
            rotation={[1.39, -0.25, -1.34]}
            scale={0.65}
          >
            <mesh
              name="개체_281003_1"
              geometry={nodes.개체_281003_1.geometry}
              material={materials["Material29.002"]}
            />
            <mesh
              name="개체_281003_2"
              geometry={nodes.개체_281003_2.geometry}
              material={materials["재질_2.003"]}
            />
            <mesh
              name="개체_281003_3"
              geometry={nodes.개체_281003_3.geometry}
              material={materials["Material_2.006"]}
            />
          </group>
          <group
            name="개체_281003"
            position={[-274.55, -2405.97, 399.19]}
            rotation={[-2.73, -0.8, -0.76]}
            scale={0.65}
          >
            <mesh
              name="개체_281004_1"
              geometry={nodes.개체_281004_1.geometry}
              material={materials["Material29.002"]}
            />
            <mesh
              name="개체_281004_2"
              geometry={nodes.개체_281004_2.geometry}
              material={materials["재질_2.003"]}
            />
            <mesh
              name="개체_281004_3"
              geometry={nodes.개체_281004_3.geometry}
              material={materials["Material_2.006"]}
            />
          </group>
          <group
            name="개체_281004"
            position={[109.64, -3418.12, 682.91]}
            rotation={[2.18, -0.61, -1.31]}
            scale={0.65}
          >
            <mesh
              name="개체_281005_1"
              geometry={nodes.개체_281005_1.geometry}
              material={materials["Material29.002"]}
            />
            <mesh
              name="개체_281005_2"
              geometry={nodes.개체_281005_2.geometry}
              material={materials["재질_2.003"]}
            />
            <mesh
              name="개체_281005_3"
              geometry={nodes.개체_281005_3.geometry}
              material={materials["Material_2.006"]}
            />
          </group>
          <group
            name="개체_281005"
            position={[432.48, -2328.66, 441.51]}
            rotation={[1.39, -0.25, -1.34]}
            scale={0.65}
          >
            <mesh
              name="개체_281006_1"
              geometry={nodes.개체_281006_1.geometry}
              material={materials["Material6.002"]}
            />
            <mesh
              name="개체_281006_2"
              geometry={nodes.개체_281006_2.geometry}
              material={materials["Material29.002"]}
            />
            <mesh
              name="개체_281006_3"
              geometry={nodes.개체_281006_3.geometry}
              material={materials["재질_2.003"]}
            />
            <mesh
              name="개체_281006_4"
              geometry={nodes.개체_281006_4.geometry}
              material={materials["Material_2.006"]}
            />
            <mesh
              name="개체_281006_5"
              geometry={nodes.개체_281006_5.geometry}
              material={materials["Material17.002"]}
            />
            <mesh
              name="개체_281006_6"
              geometry={nodes.개체_281006_6.geometry}
              material={materials["default"]}
            />
            <mesh
              name="개체_281006_7"
              geometry={nodes.개체_281006_7.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              name="개체_281006_8"
              geometry={nodes.개체_281006_8.geometry}
              material={materials["Material4.002"]}
            />
            <mesh
              name="개체_281006_9"
              geometry={nodes.개체_281006_9.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              name="개체_281006_10"
              geometry={nodes.개체_281006_10.geometry}
              material={materials["Material3.002"]}
            />
          </group>
          <group
            name="개체_281006"
            position={[432.48, -2328.66, 441.51]}
            rotation={[1.39, -0.25, -1.34]}
            scale={0.65}
          >
            <mesh
              name="개체_281007"
              geometry={nodes.개체_281007.geometry}
              material={materials["Material6.002"]}
            />
            <mesh
              name="개체_281007_1"
              geometry={nodes.개체_281007_1.geometry}
              material={materials["Material29.002"]}
            />
            <mesh
              name="개체_281007_2"
              geometry={nodes.개체_281007_2.geometry}
              material={materials["재질_2.003"]}
            />
            <mesh
              name="개체_281007_3"
              geometry={nodes.개체_281007_3.geometry}
              material={materials["Material_2.006"]}
            />
            <mesh
              name="개체_281007_4"
              geometry={nodes.개체_281007_4.geometry}
              material={materials["Material17.002"]}
            />
            <mesh
              name="개체_281007_5"
              geometry={nodes.개체_281007_5.geometry}
              material={materials["default"]}
            />
            <mesh
              name="개체_281007_6"
              geometry={nodes.개체_281007_6.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              name="개체_281007_7"
              geometry={nodes.개체_281007_7.geometry}
              material={materials["Material4.002"]}
            />
            <mesh
              name="개체_281007_8"
              geometry={nodes.개체_281007_8.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              name="개체_281007_9"
              geometry={nodes.개체_281007_9.geometry}
              material={materials["Material3.002"]}
            />
          </group>
        </group>
        <group
          name="aluminum006"
          position={[-5.91, -3.25, -78.33]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1007"
            geometry={nodes.Object_1007.geometry}
            material={materials["Material_2.004"]}
          />
        </group>
        <group
          name="black006"
          position={[-5.91, -3.25, -78.33]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3004"
            geometry={nodes.Object_3004.geometry}
            material={materials["Material_2.004"]}
            position={[336.91, 0, -179.08]}
          />
        </group>
        <group
          name="aluminum007"
          position={[11.59, -5.43, -92.15]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1009"
            geometry={nodes.Object_1009.geometry}
            material={materials["Material_2.004"]}
            position={[-2086.82, 678.59, -363.1]}
          />
          <mesh
            name="Object_1012"
            geometry={nodes.Object_1012.geometry}
            material={materials["Material_2.004"]}
            position={[-1465.26, 1661.31, -691.04]}
          />
          <mesh
            name="Object_1013"
            geometry={nodes.Object_1013.geometry}
            material={materials["Material_2.004"]}
            position={[-3129.71, 2153.92, -1057.21]}
          />
        </group>
        <group
          name="black007"
          position={[11.59, -5.43, -92.15]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3006"
            geometry={nodes.Object_3006.geometry}
            material={materials["Material_2.004"]}
            position={[-2086.82, 678.59, -363.1]}
          />
          <mesh
            name="Object_3009"
            geometry={nodes.Object_3009.geometry}
            material={materials["Material_2.004"]}
            position={[-1465.26, 1661.31, -691.04]}
          />
          <mesh
            name="Object_3010"
            geometry={nodes.Object_3010.geometry}
            material={materials["Material_2.004"]}
            position={[-3129.71, 2153.92, -1057.21]}
          />
        </group>
        <group
          name="aluminum008"
          position={[0.46, 0.16, -64.07]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1010"
            geometry={nodes.Object_1010.geometry}
            material={materials["Material_2.004"]}
          />
        </group>
        <group
          name="black008"
          position={[0.46, 0.16, -64.07]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3007"
            geometry={nodes.Object_3007.geometry}
            material={materials["Material_2.004"]}
          />
        </group>
        <group
          name="aluminum009"
          position={[3.99, -0.71, -88.1]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_1011"
            geometry={nodes.Object_1011.geometry}
            material={materials["Material_2.004"]}
            position={[-97.69, 93.51, 353.37]}
          />
        </group>
        <group
          name="black009"
          position={[3.99, -0.71, -88.1]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_3008"
            geometry={nodes.Object_3008.geometry}
            material={materials["Material_2.004"]}
            position={[-97.69, 93.51, 353.37]}
          />
        </group>
        <group
          name="BLACK"
          position={[-11.78, 2.1, 11.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Object_9"
            geometry={nodes.Object_9.geometry}
            material={materials["Material_2.007"]}
          />
          <mesh
            name="Object_9001"
            geometry={nodes.Object_9001.geometry}
            material={materials["Material_2.007"]}
            position={[-958.62, -978.03, 292.82]}
          />
        </group>
        <mesh
          name="Object_1003"
          geometry={nodes.Object_1003.geometry}
          material={materials["Material_2.005"]}
          position={[-1557.6, -241.43, -969.32]}
        />
        <mesh
          name="Object_1004"
          geometry={nodes.Object_1004.geometry}
          material={materials["Material_2.005"]}
          position={[-2128.63, -2995.37, -874.26]}
        />
        <mesh
          name="Object_1005"
          geometry={nodes.Object_1005.geometry}
          material={materials["Material_2.005"]}
          position={[-2156.72, -4601.41, -834.37]}
        />
        <group
          name="inner_sole"
          position={[-2.84, -1.16, -28.24]}
          rotation={[1.66, 0.08, 1.48]}
          scale={0.09}
        >
          <mesh
            name="inner_sole_1"
            geometry={nodes.inner_sole_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="inner_sole_2"
            geometry={nodes.inner_sole_2.geometry}
            material={materials.black_leather}
          />
          <mesh
            name="inner_sole_3"
            geometry={nodes.inner_sole_3.geometry}
            material={materials.stitching_black}
          />
          <mesh
            name="inner_sole_4"
            geometry={nodes.inner_sole_4.geometry}
            material={materials.stitching_white}
          />
          <mesh
            name="inner_sole_5"
            geometry={nodes.inner_sole_5.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="inner_sole_6"
            geometry={nodes.inner_sole_6.geometry}
            material={materials.white_leather}
          />
          <mesh
            name="inner_sole_7"
            geometry={nodes.inner_sole_7.geometry}
            material={materials["default"]}
          />
          <mesh
            name="inner_sole_8"
            geometry={nodes.inner_sole_8.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="inner_sole_9"
            geometry={nodes.inner_sole_9.geometry}
            material={materials.sole_semi_rough}
          />
          <mesh
            name="inner_sole_10"
            geometry={nodes.inner_sole_10.geometry}
            material={materials.sole_rough}
          />
          <mesh
            name="inner_sole_11"
            geometry={nodes.inner_sole_11.geometry}
            material={materials.sole_main}
          />
          <mesh
            name="inner_sole_12"
            geometry={nodes.inner_sole_12.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            name="inner_sole_13"
            geometry={nodes.inner_sole_13.geometry}
            material={materials.cream_leather}
          />
        </group>
        <group
          name="4"
          position={[3.37, -0.42, -34.38]}
          rotation={[0, -0.76, 0]}
          scale={[0.01, 0, 0]}
        >
          <mesh
            name="Mesh001"
            geometry={nodes.Mesh001.geometry}
            material={materials["Material #2673"]}
          />
          <mesh
            name="Mesh001_1"
            geometry={nodes.Mesh001_1.geometry}
            material={materials["Material #2674"]}
          />
          <mesh
            name="Mesh001_2"
            geometry={nodes.Mesh001_2.geometry}
            material={materials["Material #2675"]}
          />
          <mesh name="Mesh001_3" geometry={nodes.Mesh001_3.geometry} material={materials.yallo} />
          <mesh name="Mesh001_4" geometry={nodes.Mesh001_4.geometry} material={materials.steel} />
          <mesh
            name="Mesh001_5"
            geometry={nodes.Mesh001_5.geometry}
            material={materials["Material #2678"]}
          />
          <mesh
            name="Mesh001_6"
            geometry={nodes.Mesh001_6.geometry}
            material={materials["Material #2677"]}
          />
          <mesh name="Mesh001_7" geometry={nodes.Mesh001_7.geometry} material={materials.red} />
          <mesh
            name="Mesh001_8"
            geometry={nodes.Mesh001_8.geometry}
            material={materials.Standardmaterial_3}
          />
          <mesh name="Mesh001_9" geometry={nodes.Mesh001_9.geometry} material={materials.waith} />
          <mesh name="Mesh001_10" geometry={nodes.Mesh001_10.geometry} material={materials.green} />
          <mesh
            name="Mesh001_11"
            geometry={nodes.Mesh001_11.geometry}
            material={materials["Material #2672"]}
          />
          <mesh
            name="Mesh001_12"
            geometry={nodes.Mesh001_12.geometry}
            material={materials["Material #2676"]}
          />
          <mesh
            name="Mesh001_13"
            geometry={nodes.Mesh001_13.geometry}
            material={materials["Material #2679"]}
          />
          <mesh name="Mesh001_14" geometry={nodes.Mesh001_14.geometry} material={materials.saman} />
          <mesh
            name="Mesh001_15"
            geometry={nodes.Mesh001_15.geometry}
            material={materials["Material #25"]}
          />
          <mesh
            name="Mesh001_16"
            geometry={nodes.Mesh001_16.geometry}
            material={materials["Material #2681"]}
          />
          <mesh
            name="Mesh001_17"
            geometry={nodes.Mesh001_17.geometry}
            material={materials["Material #2682"]}
          />
        </group>
        <group name="개체_282" position={[-4.75, 8.62, -0.76]}>
          <mesh
            name="개체_282002_1"
            geometry={nodes.개체_282002_1.geometry}
            material={materials.Material17}
          />
          <mesh
            name="개체_282002_2"
            geometry={nodes.개체_282002_2.geometry}
            material={materials.Material29}
          />
          <mesh
            name="개체_282002_3"
            geometry={nodes.개체_282002_3.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_282002_4"
            geometry={nodes.개체_282002_4.geometry}
            material={materials.Material_2}
          />
          <mesh
            name="개체_282002_5"
            geometry={nodes.개체_282002_5.geometry}
            material={materials.Material6}
          />
          <mesh
            name="개체_282002_6"
            geometry={nodes.개체_282002_6.geometry}
            material={materials["default"]}
          />
          <mesh
            name="개체_282002_7"
            geometry={nodes.개체_282002_7.geometry}
            material={materials.Material}
          />
          <mesh
            name="개체_282002_8"
            geometry={nodes.개체_282002_8.geometry}
            material={materials.Material4}
          />
          <mesh
            name="개체_282002_9"
            geometry={nodes.개체_282002_9.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="개체_282002_10"
            geometry={nodes.개체_282002_10.geometry}
            material={materials.Material3}
          />
        </group>
        <group name="개체_282001" position={[-4.75, 8.62, -0.76]}>
          <mesh
            name="개체_282001_1"
            geometry={nodes.개체_282001_1.geometry}
            material={materials["Material17.001"]}
          />
          <mesh
            name="개체_282001_2"
            geometry={nodes.개체_282001_2.geometry}
            material={materials["Material29.001"]}
          />
          <mesh
            name="개체_282001_3"
            geometry={nodes.개체_282001_3.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_282001_4"
            geometry={nodes.개체_282001_4.geometry}
            material={materials["Material_2.001"]}
          />
          <mesh
            name="개체_282001_5"
            geometry={nodes.개체_282001_5.geometry}
            material={materials["Material6.001"]}
          />
          <mesh
            name="개체_282001_6"
            geometry={nodes.개체_282001_6.geometry}
            material={materials["default"]}
          />
          <mesh
            name="개체_282001_7"
            geometry={nodes.개체_282001_7.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="개체_282001_8"
            geometry={nodes.개체_282001_8.geometry}
            material={materials["Material4.001"]}
          />
          <mesh
            name="개체_282001_9"
            geometry={nodes.개체_282001_9.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="개체_282001_10"
            geometry={nodes.개체_282001_10.geometry}
            material={materials["Material3.001"]}
          />
        </group>
        <group name="개체_282002" position={[260.57, -146.9, 4.84]} scale={3.24}>
          <mesh
            name="개체_282003"
            geometry={nodes.개체_282003.geometry}
            material={materials.Material29}
          />
          <mesh
            name="개체_282003_1"
            geometry={nodes.개체_282003_1.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_282003_2"
            geometry={nodes.개체_282003_2.geometry}
            material={materials.Material_2}
          />
          <mesh
            name="개체_282003_3"
            geometry={nodes.개체_282003_3.geometry}
            material={materials.Material6}
          />
        </group>
        <group
          name="4001"
          position={[-11.69, -1.2, -82.99]}
          rotation={[-0.48, -0.78, -0.43]}
          scale={0}
        >
          <mesh
            name="Mesh002"
            geometry={nodes.Mesh002.geometry}
            material={materials["Material #2673"]}
          />
          <mesh
            name="Mesh002_1"
            geometry={nodes.Mesh002_1.geometry}
            material={materials["Material #2674"]}
          />
          <mesh
            name="Mesh002_2"
            geometry={nodes.Mesh002_2.geometry}
            material={materials["Material #2675"]}
          />
          <mesh name="Mesh002_3" geometry={nodes.Mesh002_3.geometry} material={materials.yallo} />
          <mesh name="Mesh002_4" geometry={nodes.Mesh002_4.geometry} material={materials.steel} />
          <mesh
            name="Mesh002_5"
            geometry={nodes.Mesh002_5.geometry}
            material={materials["Material #2678"]}
          />
          <mesh
            name="Mesh002_6"
            geometry={nodes.Mesh002_6.geometry}
            material={materials["Material #2677"]}
          />
          <mesh name="Mesh002_7" geometry={nodes.Mesh002_7.geometry} material={materials.red} />
          <mesh
            name="Mesh002_8"
            geometry={nodes.Mesh002_8.geometry}
            material={materials.Standardmaterial_3}
          />
          <mesh name="Mesh002_9" geometry={nodes.Mesh002_9.geometry} material={materials.waith} />
          <mesh name="Mesh002_10" geometry={nodes.Mesh002_10.geometry} material={materials.green} />
          <mesh
            name="Mesh002_11"
            geometry={nodes.Mesh002_11.geometry}
            material={materials["Material #2672"]}
          />
          <mesh
            name="Mesh002_12"
            geometry={nodes.Mesh002_12.geometry}
            material={materials["Material #2676"]}
          />
          <mesh
            name="Mesh002_13"
            geometry={nodes.Mesh002_13.geometry}
            material={materials["Material #2679"]}
          />
          <mesh name="Mesh002_14" geometry={nodes.Mesh002_14.geometry} material={materials.saman} />
          <mesh
            name="Mesh002_15"
            geometry={nodes.Mesh002_15.geometry}
            material={materials["Material #25"]}
          />
          <mesh
            name="Mesh002_16"
            geometry={nodes.Mesh002_16.geometry}
            material={materials["Material #2681"]}
          />
          <mesh
            name="Mesh002_17"
            geometry={nodes.Mesh002_17.geometry}
            material={materials["Material #2682"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sajana2.gltf");
