/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Sunyena(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/sunyena-draco.gltf");
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="cool_gray"
          position={[1.78, 0.87, 0.91]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1"
            geometry={nodes.Object_1.geometry}
            material={materials.Material_2}
          />
          <mesh
            name="Object_1001"
            geometry={nodes.Object_1001.geometry}
            material={materials.Material_2}
            position={[0, -17.91, 0]}
          />
          <mesh
            name="Object_1002"
            geometry={nodes.Object_1002.geometry}
            material={materials.Material_2}
            position={[0, -31.35, 0]}
          />
          <mesh
            name="Object_1003"
            geometry={nodes.Object_1003.geometry}
            material={materials.Material_2}
            position={[-57.09, -50.58, -25.89]}
          />
          <mesh
            name="Object_1004"
            geometry={nodes.Object_1004.geometry}
            material={materials.Material_2}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1005"
            geometry={nodes.Object_1005.geometry}
            material={materials.Material_2}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1006"
            geometry={nodes.Object_1006.geometry}
            material={materials.Material_2}
            position={[0, -95.58, 0]}
          />
          <mesh
            name="Object_1007"
            geometry={nodes.Object_1007.geometry}
            material={materials.Material_2}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1008"
            geometry={nodes.Object_1008.geometry}
            material={materials.Material_2}
            position={[0, -128.23, 0]}
          />
          <mesh
            name="Object_1009"
            geometry={nodes.Object_1009.geometry}
            material={materials.Material_2}
            position={[5.21, -191.09, -64.39]}
          />
          <mesh
            name="Object_1010"
            geometry={nodes.Object_1010.geometry}
            material={materials.Material_2}
            position={[0, -159.58, 0]}
          />
          <mesh
            name="Object_1011"
            geometry={nodes.Object_1011.geometry}
            material={materials.Material_2}
            position={[0, -177.49, 0]}
          />
          <mesh
            name="Object_1012"
            geometry={nodes.Object_1012.geometry}
            material={materials.Material_2}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1013"
            geometry={nodes.Object_1013.geometry}
            material={materials.Material_2}
            position={[0, -210.38, 0]}
          />
          <mesh
            name="Object_1014"
            geometry={nodes.Object_1014.geometry}
            material={materials.Material_2}
            position={[0, -223.81, 0]}
          />
          <mesh
            name="Object_1015"
            geometry={nodes.Object_1015.geometry}
            material={materials.Material_2}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1016"
            geometry={nodes.Object_1016.geometry}
            material={materials.Material_2}
            position={[0, 259.39, 0]}
          />
          <mesh
            name="Object_1017"
            geometry={nodes.Object_1017.geometry}
            material={materials.Material_2}
            position={[0, 241.48, 0]}
          />
          <mesh
            name="Object_1018"
            geometry={nodes.Object_1018.geometry}
            material={materials.Material_2}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1019"
            geometry={nodes.Object_1019.geometry}
            material={materials.Material_2}
            position={[0, 210.13, 0]}
          />
          <mesh
            name="Object_1020"
            geometry={nodes.Object_1020.geometry}
            material={materials.Material_2}
            position={[43.56, -0.35, 70.08]}
          />
          <mesh
            name="Object_1021"
            geometry={nodes.Object_1021.geometry}
            material={materials.Material_2}
            position={[0, 177.24, 0]}
          />
          <mesh
            name="Object_1022"
            geometry={nodes.Object_1022.geometry}
            material={materials.Material_2}
            position={[0, 163.81, 0]}
          />
          <mesh
            name="Object_1023"
            geometry={nodes.Object_1023.geometry}
            material={materials.Material_2}
            position={[0, 145.89, 0]}
          />
          <mesh
            name="Object_1024"
            geometry={nodes.Object_1024.geometry}
            material={materials.Material_2}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1025"
            geometry={nodes.Object_1025.geometry}
            material={materials.Material_2}
            position={[0, 113.25, 0]}
          />
          <mesh
            name="Object_1026"
            geometry={nodes.Object_1026.geometry}
            material={materials.Material_2}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1027"
            geometry={nodes.Object_1027.geometry}
            material={materials.Material_2}
            position={[0, 81.9, 0]}
          />
          <mesh
            name="Object_1028"
            geometry={nodes.Object_1028.geometry}
            material={materials.Material_2}
            position={[0, 66.93, 0]}
          />
          <mesh
            name="Object_1029"
            geometry={nodes.Object_1029.geometry}
            material={materials.Material_2}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1030"
            geometry={nodes.Object_1030.geometry}
            material={materials.Material_2}
            position={[0, 35.58, 0]}
          />
          <mesh
            name="Object_1031"
            geometry={nodes.Object_1031.geometry}
            material={materials.Material_2}
            position={[0, 17.66, 0]}
          />
          <mesh
            name="Object_1174"
            geometry={nodes.Object_1174.geometry}
            material={materials.Material_2}
            position={[312.31, -397.17, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1175"
            geometry={nodes.Object_1175.geometry}
            material={materials.Material_2}
            position={[312.31, -413.63, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1176"
            geometry={nodes.Object_1176.geometry}
            material={materials.Material_2}
            position={[312.31, -425.98, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1177"
            geometry={nodes.Object_1177.geometry}
            material={materials.Material_2}
            position={[312.31, -456.2, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1178"
            geometry={nodes.Object_1178.geometry}
            material={materials.Material_2}
            position={[312.31, -472.66, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1179"
            geometry={nodes.Object_1179.geometry}
            material={materials.Material_2}
            position={[-126.06, -54.57, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1180"
            geometry={nodes.Object_1180.geometry}
            material={materials.Material_2}
            position={[-126.06, -71.03, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1181"
            geometry={nodes.Object_1181.geometry}
            material={materials.Material_2}
            position={[-126.06, -84.57, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1182"
            geometry={nodes.Object_1182.geometry}
            material={materials.Material_2}
            position={[-126.06, -113.38, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1183"
            geometry={nodes.Object_1183.geometry}
            material={materials.Material_2}
            position={[-126.06, -129.84, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1184"
            geometry={nodes.Object_1184.geometry}
            material={materials.Material_2}
            position={[-126.06, 271.61, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1185"
            geometry={nodes.Object_1185.geometry}
            material={materials.Material_2}
            position={[-126.06, 255.15, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1186"
            geometry={nodes.Object_1186.geometry}
            material={materials.Material_2}
            position={[-126.06, 242.81, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1187"
            geometry={nodes.Object_1187.geometry}
            material={materials.Material_2}
            position={[-126.06, 226.35, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1188"
            geometry={nodes.Object_1188.geometry}
            material={materials.Material_2}
            position={[-126.06, 196.13, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1189"
            geometry={nodes.Object_1189.geometry}
            material={materials.Material_2}
            position={[-126.06, 183.78, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1190"
            geometry={nodes.Object_1190.geometry}
            material={materials.Material_2}
            position={[73.03, 145.47, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1191"
            geometry={nodes.Object_1191.geometry}
            material={materials.Material_2}
            position={[73.03, 131.93, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1192"
            geometry={nodes.Object_1192.geometry}
            material={materials.Material_2}
            position={[73.03, 115.47, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1193"
            geometry={nodes.Object_1193.geometry}
            material={materials.Material_2}
            position={[73.03, 103.12, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1194"
            geometry={nodes.Object_1194.geometry}
            material={materials.Material_2}
            position={[73.03, 86.66, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1195"
            geometry={nodes.Object_1195.geometry}
            material={materials.Material_2}
            position={[73.03, 72.91, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1196"
            geometry={nodes.Object_1196.geometry}
            material={materials.Material_2}
            position={[73.03, 56.45, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1197"
            geometry={nodes.Object_1197.geometry}
            material={materials.Material_2}
            position={[73.03, 44.1, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1198"
            geometry={nodes.Object_1198.geometry}
            material={materials.Material_2}
            position={[73.03, 27.64, 124.14]}
            scale={0.92}
          />
        </group>
        <group
          name="cool_gray001"
          position={[1.79, 0.79, -11.12]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1032"
            geometry={nodes.Object_1032.geometry}
            material={materials.Material_2}
          />
          <mesh
            name="Object_1033"
            geometry={nodes.Object_1033.geometry}
            material={materials.Material_2}
            position={[0, -17.91, 0]}
          />
          <mesh
            name="Object_1034"
            geometry={nodes.Object_1034.geometry}
            material={materials.Material_2}
            position={[0, -31.35, 0]}
          />
          <mesh
            name="Object_1035"
            geometry={nodes.Object_1035.geometry}
            material={materials.Material_2}
            position={[0, -49.26, 0]}
          />
          <mesh
            name="Object_1036"
            geometry={nodes.Object_1036.geometry}
            material={materials.Material_2}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1037"
            geometry={nodes.Object_1037.geometry}
            material={materials.Material_2}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1038"
            geometry={nodes.Object_1038.geometry}
            material={materials.Material_2}
            position={[0, -95.58, 0]}
          />
          <mesh
            name="Object_1039"
            geometry={nodes.Object_1039.geometry}
            material={materials.Material_2}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1040"
            geometry={nodes.Object_1040.geometry}
            material={materials.Material_2}
            position={[0, -128.23, 0]}
          />
          <mesh
            name="Object_1041"
            geometry={nodes.Object_1041.geometry}
            material={materials.Material_2}
            position={[-133.04, -684.45, 109.9]}
          />
          <mesh
            name="Object_1042"
            geometry={nodes.Object_1042.geometry}
            material={materials.Material_2}
            position={[0, -159.58, 0]}
          />
          <mesh
            name="Object_1043"
            geometry={nodes.Object_1043.geometry}
            material={materials.Material_2}
            position={[-164.46, -136.61, -22.51]}
          />
          <mesh
            name="Object_1044"
            geometry={nodes.Object_1044.geometry}
            material={materials.Material_2}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1045"
            geometry={nodes.Object_1045.geometry}
            material={materials.Material_2}
            position={[0, -210.38, 0]}
          />
          <mesh
            name="Object_1046"
            geometry={nodes.Object_1046.geometry}
            material={materials.Material_2}
            position={[-140.37, -593.81, 93.47]}
          />
          <mesh
            name="Object_1047"
            geometry={nodes.Object_1047.geometry}
            material={materials.Material_2}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1048"
            geometry={nodes.Object_1048.geometry}
            material={materials.Material_2}
            position={[0, 259.39, 0]}
          />
          <mesh
            name="Object_1049"
            geometry={nodes.Object_1049.geometry}
            material={materials.Material_2}
            position={[0, 241.48, 0]}
          />
          <mesh
            name="Object_1050"
            geometry={nodes.Object_1050.geometry}
            material={materials.Material_2}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1051"
            geometry={nodes.Object_1051.geometry}
            material={materials.Material_2}
            position={[0, 210.13, 0]}
          />
          <mesh
            name="Object_1052"
            geometry={nodes.Object_1052.geometry}
            material={materials.Material_2}
            position={[0, 195.16, 0]}
          />
          <mesh
            name="Object_1053"
            geometry={nodes.Object_1053.geometry}
            material={materials.Material_2}
            position={[0, 177.24, 0]}
          />
          <mesh
            name="Object_1054"
            geometry={nodes.Object_1054.geometry}
            material={materials.Material_2}
            position={[0, 163.81, 0]}
          />
          <mesh
            name="Object_1055"
            geometry={nodes.Object_1055.geometry}
            material={materials.Material_2}
            position={[-69.23, 111.8, 146.39]}
          />
          <mesh
            name="Object_1056"
            geometry={nodes.Object_1056.geometry}
            material={materials.Material_2}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1057"
            geometry={nodes.Object_1057.geometry}
            material={materials.Material_2}
            position={[0, 113.25, 0]}
          />
          <mesh
            name="Object_1058"
            geometry={nodes.Object_1058.geometry}
            material={materials.Material_2}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1059"
            geometry={nodes.Object_1059.geometry}
            material={materials.Material_2}
            position={[-94, -111.97, -108.47]}
          />
          <mesh
            name="Object_1060"
            geometry={nodes.Object_1060.geometry}
            material={materials.Material_2}
            position={[0, 66.93, 0]}
          />
          <mesh
            name="Object_1061"
            geometry={nodes.Object_1061.geometry}
            material={materials.Material_2}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1062"
            geometry={nodes.Object_1062.geometry}
            material={materials.Material_2}
            position={[-197.1, -483.44, 130.82]}
          />
          <mesh
            name="Object_1063"
            geometry={nodes.Object_1063.geometry}
            material={materials.Material_2}
            position={[-239.39, -667.17, -4.2]}
          />
          <mesh
            name="Object_1199"
            geometry={nodes.Object_1199.geometry}
            material={materials.Material_2}
            position={[-189.73, 177.88, 260.27]}
            scale={0.92}
          />
        </group>
        <group
          name="cool_gray003"
          position={[1.78, 0.87, 0.91]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1096"
            geometry={nodes.Object_1096.geometry}
            material={materials["Material_2.001"]}
            position={[0, 17.66, 0]}
          />
          <mesh
            name="Object_1097"
            geometry={nodes.Object_1097.geometry}
            material={materials["Material_2.001"]}
            position={[0, 35.58, 0]}
          />
          <mesh
            name="Object_1098"
            geometry={nodes.Object_1098.geometry}
            material={materials["Material_2.001"]}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1099"
            geometry={nodes.Object_1099.geometry}
            material={materials["Material_2.001"]}
            position={[0, 66.93, 0]}
          />
          <mesh
            name="Object_1100"
            geometry={nodes.Object_1100.geometry}
            material={materials["Material_2.001"]}
            position={[0, 81.9, 0]}
          />
          <mesh
            name="Object_1101"
            geometry={nodes.Object_1101.geometry}
            material={materials["Material_2.001"]}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1102"
            geometry={nodes.Object_1102.geometry}
            material={materials["Material_2.001"]}
            position={[0, 113.25, 0]}
          />
          <mesh
            name="Object_1103"
            geometry={nodes.Object_1103.geometry}
            material={materials["Material_2.001"]}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1104"
            geometry={nodes.Object_1104.geometry}
            material={materials["Material_2.001"]}
            position={[-15.11, -234.97, 80.08]}
          />
          <mesh
            name="Object_1105"
            geometry={nodes.Object_1105.geometry}
            material={materials["Material_2.001"]}
            position={[0, -210.38, 0]}
          />
          <mesh
            name="Object_1106"
            geometry={nodes.Object_1106.geometry}
            material={materials["Material_2.001"]}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1107"
            geometry={nodes.Object_1107.geometry}
            material={materials["Material_2.001"]}
            position={[0, -177.49, 0]}
          />
          <mesh
            name="Object_1108"
            geometry={nodes.Object_1108.geometry}
            material={materials["Material_2.001"]}
            position={[0, -159.58, 0]}
          />
          <mesh
            name="Object_1109"
            geometry={nodes.Object_1109.geometry}
            material={materials["Material_2.001"]}
            position={[0, -146.14, 0]}
          />
          <mesh
            name="Object_1110"
            geometry={nodes.Object_1110.geometry}
            material={materials["Material_2.001"]}
            position={[0, -128.23, 0]}
          />
          <mesh
            name="Object_1111"
            geometry={nodes.Object_1111.geometry}
            material={materials["Material_2.001"]}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1112"
            geometry={nodes.Object_1112.geometry}
            material={materials["Material_2.001"]}
            position={[0, -95.58, 0]}
          />
          <mesh
            name="Object_1113"
            geometry={nodes.Object_1113.geometry}
            material={materials["Material_2.001"]}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1114"
            geometry={nodes.Object_1114.geometry}
            material={materials["Material_2.001"]}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1115"
            geometry={nodes.Object_1115.geometry}
            material={materials["Material_2.001"]}
            position={[0, -49.26, 0]}
          />
          <mesh
            name="Object_1116"
            geometry={nodes.Object_1116.geometry}
            material={materials["Material_2.001"]}
            position={[0, -31.35, 0]}
          />
          <mesh
            name="Object_1117"
            geometry={nodes.Object_1117.geometry}
            material={materials["Material_2.001"]}
            position={[0, -17.91, 0]}
          />
          <mesh
            name="Object_1118"
            geometry={nodes.Object_1118.geometry}
            material={materials["Material_2.001"]}
          />
          <mesh
            name="Object_1200"
            geometry={nodes.Object_1200.geometry}
            material={materials["Material_2.001"]}
            position={[312.31, -397.17, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1201"
            geometry={nodes.Object_1201.geometry}
            material={materials["Material_2.001"]}
            position={[312.31, -413.63, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1202"
            geometry={nodes.Object_1202.geometry}
            material={materials["Material_2.001"]}
            position={[312.31, -425.98, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1203"
            geometry={nodes.Object_1203.geometry}
            material={materials["Material_2.001"]}
            position={[312.31, -442.44, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1204"
            geometry={nodes.Object_1204.geometry}
            material={materials["Material_2.001"]}
            position={[312.31, -456.2, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1205"
            geometry={nodes.Object_1205.geometry}
            material={materials["Material_2.001"]}
            position={[312.31, -472.66, 12.11]}
            scale={0.92}
          />
          <mesh
            name="Object_1206"
            geometry={nodes.Object_1206.geometry}
            material={materials["Material_2.001"]}
            position={[-126.06, -54.57, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1207"
            geometry={nodes.Object_1207.geometry}
            material={materials["Material_2.001"]}
            position={[-126.06, -71.03, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1208"
            geometry={nodes.Object_1208.geometry}
            material={materials["Material_2.001"]}
            position={[-126.06, -84.57, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1209"
            geometry={nodes.Object_1209.geometry}
            material={materials["Material_2.001"]}
            position={[-126.06, -101.03, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1210"
            geometry={nodes.Object_1210.geometry}
            material={materials["Material_2.001"]}
            position={[-126.06, -113.38, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1211"
            geometry={nodes.Object_1211.geometry}
            material={materials["Material_2.001"]}
            position={[-126.06, -129.84, 126.02]}
            scale={0.92}
          />
          <mesh
            name="Object_1212"
            geometry={nodes.Object_1212.geometry}
            material={materials["Material_2.001"]}
            position={[59.15, -204.51, 197.73]}
            scale={0.92}
          />
          <mesh
            name="Object_1213"
            geometry={nodes.Object_1213.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 115.47, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1214"
            geometry={nodes.Object_1214.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 103.12, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1215"
            geometry={nodes.Object_1215.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 86.66, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1216"
            geometry={nodes.Object_1216.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 72.91, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1217"
            geometry={nodes.Object_1217.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 56.45, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1218"
            geometry={nodes.Object_1218.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 44.1, 124.14]}
            scale={0.92}
          />
          <mesh
            name="Object_1219"
            geometry={nodes.Object_1219.geometry}
            material={materials["Material_2.001"]}
            position={[73.03, 27.64, 124.14]}
            scale={0.92}
          />
        </group>
        <group
          name="cool_gray002"
          position={[1.79, 0.79, -11.12]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1064"
            geometry={nodes.Object_1064.geometry}
            material={materials["Material_2.001"]}
            position={[0, 17.66, 0]}
          />
          <mesh
            name="Object_1065"
            geometry={nodes.Object_1065.geometry}
            material={materials["Material_2.001"]}
            position={[0, 35.58, 0]}
          />
          <mesh
            name="Object_1066"
            geometry={nodes.Object_1066.geometry}
            material={materials["Material_2.001"]}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1067"
            geometry={nodes.Object_1067.geometry}
            material={materials["Material_2.001"]}
            position={[0, 66.93, 0]}
          />
          <mesh
            name="Object_1068"
            geometry={nodes.Object_1068.geometry}
            material={materials["Material_2.001"]}
            position={[0, 81.9, 0]}
          />
          <mesh
            name="Object_1069"
            geometry={nodes.Object_1069.geometry}
            material={materials["Material_2.001"]}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1070"
            geometry={nodes.Object_1070.geometry}
            material={materials["Material_2.001"]}
            position={[0, 113.25, 0]}
          />
          <mesh
            name="Object_1071"
            geometry={nodes.Object_1071.geometry}
            material={materials["Material_2.001"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1072"
            geometry={nodes.Object_1072.geometry}
            material={materials["Material_2.001"]}
            position={[0, 145.89, 0]}
          />
          <mesh
            name="Object_1073"
            geometry={nodes.Object_1073.geometry}
            material={materials["Material_2.001"]}
            position={[65.21, 161.99, 0]}
          />
          <mesh
            name="Object_1074"
            geometry={nodes.Object_1074.geometry}
            material={materials["Material_2.001"]}
            position={[0, 177.24, 0]}
          />
          <mesh
            name="Object_1075"
            geometry={nodes.Object_1075.geometry}
            material={materials["Material_2.001"]}
            position={[0, 195.16, 0]}
          />
          <mesh
            name="Object_1076"
            geometry={nodes.Object_1076.geometry}
            material={materials["Material_2.001"]}
            position={[0, 210.13, 0]}
          />
          <mesh
            name="Object_1077"
            geometry={nodes.Object_1077.geometry}
            material={materials["Material_2.001"]}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1078"
            geometry={nodes.Object_1078.geometry}
            material={materials["Material_2.001"]}
            position={[0, 241.48, 0]}
          />
          <mesh
            name="Object_1079"
            geometry={nodes.Object_1079.geometry}
            material={materials["Material_2.001"]}
            position={[0, 259.39, 0]}
          />
          <mesh
            name="Object_1080"
            geometry={nodes.Object_1080.geometry}
            material={materials["Material_2.001"]}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1081"
            geometry={nodes.Object_1081.geometry}
            material={materials["Material_2.001"]}
            position={[0, -223.81, 0]}
          />
          <mesh
            name="Object_1082"
            geometry={nodes.Object_1082.geometry}
            material={materials["Material_2.001"]}
            position={[0, -210.38, 0]}
          />
          <mesh
            name="Object_1083"
            geometry={nodes.Object_1083.geometry}
            material={materials["Material_2.001"]}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1084"
            geometry={nodes.Object_1084.geometry}
            material={materials["Material_2.001"]}
            position={[0, -177.49, 0]}
          />
          <mesh
            name="Object_1085"
            geometry={nodes.Object_1085.geometry}
            material={materials["Material_2.001"]}
            position={[0, -159.58, 0]}
          />
          <mesh
            name="Object_1086"
            geometry={nodes.Object_1086.geometry}
            material={materials["Material_2.001"]}
            position={[0, -146.14, 0]}
          />
          <mesh
            name="Object_1087"
            geometry={nodes.Object_1087.geometry}
            material={materials["Material_2.001"]}
            position={[0, -128.23, 0]}
          />
          <mesh
            name="Object_1088"
            geometry={nodes.Object_1088.geometry}
            material={materials["Material_2.001"]}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1089"
            geometry={nodes.Object_1089.geometry}
            material={materials["Material_2.001"]}
            position={[0, -95.58, 0]}
          />
          <mesh
            name="Object_1090"
            geometry={nodes.Object_1090.geometry}
            material={materials["Material_2.001"]}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1091"
            geometry={nodes.Object_1091.geometry}
            material={materials["Material_2.001"]}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1092"
            geometry={nodes.Object_1092.geometry}
            material={materials["Material_2.001"]}
            position={[0, -49.26, 0]}
          />
          <mesh
            name="Object_1093"
            geometry={nodes.Object_1093.geometry}
            material={materials["Material_2.001"]}
            position={[0, -31.35, 0]}
          />
          <mesh
            name="Object_1094"
            geometry={nodes.Object_1094.geometry}
            material={materials["Material_2.001"]}
            position={[0, -17.91, 0]}
          />
          <mesh
            name="Object_1095"
            geometry={nodes.Object_1095.geometry}
            material={materials["Material_2.001"]}
          />
        </group>
        <group
          name="cool_gray004"
          position={[2.28, -0.1, -35.42]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.03}
        >
          <mesh
            name="Object_1119"
            geometry={nodes.Object_1119.geometry}
            material={materials["Material_2.001"]}
          />
          <mesh
            name="Object_1120"
            geometry={nodes.Object_1120.geometry}
            material={materials["Material_2.001"]}
            position={[0, -17.91, 0]}
          />
          <mesh
            name="Object_1121"
            geometry={nodes.Object_1121.geometry}
            material={materials["Material_2.001"]}
            position={[0, -31.35, 0]}
          />
          <mesh
            name="Object_1122"
            geometry={nodes.Object_1122.geometry}
            material={materials["Material_2.001"]}
            position={[0, -49.26, 0]}
          />
          <mesh
            name="Object_1123"
            geometry={nodes.Object_1123.geometry}
            material={materials["Material_2.001"]}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1124"
            geometry={nodes.Object_1124.geometry}
            material={materials["Material_2.001"]}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1125"
            geometry={nodes.Object_1125.geometry}
            material={materials["Material_2.001"]}
            position={[0, -95.58, 0]}
          />
          <mesh
            name="Object_1126"
            geometry={nodes.Object_1126.geometry}
            material={materials["Material_2.001"]}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1127"
            geometry={nodes.Object_1127.geometry}
            material={materials["Material_2.001"]}
            position={[0, -128.23, 0]}
          />
          <mesh
            name="Object_1128"
            geometry={nodes.Object_1128.geometry}
            material={materials["Material_2.001"]}
            position={[0, -146.14, 0]}
          />
          <mesh
            name="Object_1129"
            geometry={nodes.Object_1129.geometry}
            material={materials["Material_2.001"]}
            position={[98.63, -194.56, -17.78]}
          />
          <mesh
            name="Object_1130"
            geometry={nodes.Object_1130.geometry}
            material={materials["Material_2.001"]}
            position={[73.97, -216.74, -226.28]}
          />
          <mesh
            name="Object_1131"
            geometry={nodes.Object_1131.geometry}
            material={materials["Material_2.001"]}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1132"
            geometry={nodes.Object_1132.geometry}
            material={materials["Material_2.001"]}
            position={[-133.74, -188.51, -52.33]}
          />
          <mesh
            name="Object_1133"
            geometry={nodes.Object_1133.geometry}
            material={materials["Material_2.001"]}
            position={[0, -223.81, 0]}
          />
          <mesh
            name="Object_1134"
            geometry={nodes.Object_1134.geometry}
            material={materials["Material_2.001"]}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1135"
            geometry={nodes.Object_1135.geometry}
            material={materials["Material_2.001"]}
            position={[-125.62, 82.95, 22.97]}
          />
          <mesh
            name="Object_1136"
            geometry={nodes.Object_1136.geometry}
            material={materials["Material_2.001"]}
            position={[-3.96, 89.51, -153.3]}
          />
          <mesh
            name="Object_1137"
            geometry={nodes.Object_1137.geometry}
            material={materials["Material_2.001"]}
            position={[0, 81.9, 0]}
          />
          <mesh
            name="Object_1138"
            geometry={nodes.Object_1138.geometry}
            material={materials["Material_2.001"]}
            position={[0, 66.93, 0]}
          />
          <mesh
            name="Object_1139"
            geometry={nodes.Object_1139.geometry}
            material={materials["Material_2.001"]}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1140"
            geometry={nodes.Object_1140.geometry}
            material={materials["Material_2.001"]}
            position={[0, 35.58, 0]}
          />
          <mesh
            name="Object_1141"
            geometry={nodes.Object_1141.geometry}
            material={materials["Material_2.001"]}
            position={[0, 17.66, 0]}
          />
        </group>
        <group
          name="cool_gray005"
          position={[2.38, -0.01, -52.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.03}
        >
          <mesh
            name="Object_1142"
            geometry={nodes.Object_1142.geometry}
            material={materials["Material_2.001"]}
          />
          <mesh
            name="Object_1143"
            geometry={nodes.Object_1143.geometry}
            material={materials["Material_2.001"]}
            position={[0, -17.91, 0]}
          />
          <mesh
            name="Object_1144"
            geometry={nodes.Object_1144.geometry}
            material={materials["Material_2.001"]}
            position={[0, -31.35, 0]}
          />
          <mesh
            name="Object_1145"
            geometry={nodes.Object_1145.geometry}
            material={materials["Material_2.001"]}
            position={[0, -49.26, 0]}
          />
          <mesh
            name="Object_1146"
            geometry={nodes.Object_1146.geometry}
            material={materials["Material_2.001"]}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1147"
            geometry={nodes.Object_1147.geometry}
            material={materials["Material_2.001"]}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1148"
            geometry={nodes.Object_1148.geometry}
            material={materials["Material_2.001"]}
            position={[0, -95.58, 0]}
          />
          <mesh
            name="Object_1149"
            geometry={nodes.Object_1149.geometry}
            material={materials["Material_2.001"]}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1150"
            geometry={nodes.Object_1150.geometry}
            material={materials["Material_2.001"]}
            position={[0, -128.23, 0]}
          />
          <mesh
            name="Object_1151"
            geometry={nodes.Object_1151.geometry}
            material={materials["Material_2.001"]}
            position={[-31.16, -153.36, -48.99]}
          />
          <mesh
            name="Object_1152"
            geometry={nodes.Object_1152.geometry}
            material={materials["Material_2.001"]}
            position={[0, -159.58, 0]}
          />
          <mesh
            name="Object_1153"
            geometry={nodes.Object_1153.geometry}
            material={materials["Material_2.001"]}
            position={[0, -177.49, 0]}
          />
          <mesh
            name="Object_1154"
            geometry={nodes.Object_1154.geometry}
            material={materials["Material_2.001"]}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1155"
            geometry={nodes.Object_1155.geometry}
            material={materials["Material_2.001"]}
            position={[0, -210.38, 0]}
          />
          <mesh
            name="Object_1156"
            geometry={nodes.Object_1156.geometry}
            material={materials["Material_2.001"]}
            position={[0, -223.81, 0]}
          />
          <mesh
            name="Object_1157"
            geometry={nodes.Object_1157.geometry}
            material={materials["Material_2.001"]}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1158"
            geometry={nodes.Object_1158.geometry}
            material={materials["Material_2.001"]}
            position={[0, 259.39, 0]}
          />
          <mesh
            name="Object_1159"
            geometry={nodes.Object_1159.geometry}
            material={materials["Material_2.001"]}
            position={[-1.94, 275.85, 101.06]}
          />
          <mesh
            name="Object_1160"
            geometry={nodes.Object_1160.geometry}
            material={materials["Material_2.001"]}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1161"
            geometry={nodes.Object_1161.geometry}
            material={materials["Material_2.001"]}
            position={[0, 210.13, 0]}
          />
          <mesh
            name="Object_1162"
            geometry={nodes.Object_1162.geometry}
            material={materials["Material_2.001"]}
            position={[0, 195.16, 0]}
          />
          <mesh
            name="Object_1163"
            geometry={nodes.Object_1163.geometry}
            material={materials["Material_2.001"]}
            position={[0, 177.24, 0]}
          />
          <mesh
            name="Object_1164"
            geometry={nodes.Object_1164.geometry}
            material={materials["Material_2.001"]}
            position={[0, 163.81, 0]}
          />
          <mesh
            name="Object_1165"
            geometry={nodes.Object_1165.geometry}
            material={materials["Material_2.001"]}
            position={[0, 145.89, 0]}
          />
          <mesh
            name="Object_1166"
            geometry={nodes.Object_1166.geometry}
            material={materials["Material_2.001"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1167"
            geometry={nodes.Object_1167.geometry}
            material={materials["Material_2.001"]}
            position={[0, 113.25, 0]}
          />
          <mesh
            name="Object_1168"
            geometry={nodes.Object_1168.geometry}
            material={materials["Material_2.001"]}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1169"
            geometry={nodes.Object_1169.geometry}
            material={materials["Material_2.001"]}
            position={[0, 81.9, 0]}
          />
          <mesh
            name="Object_1170"
            geometry={nodes.Object_1170.geometry}
            material={materials["Material_2.001"]}
            position={[118.52, 24.94, -21.22]}
          />
          <mesh
            name="Object_1171"
            geometry={nodes.Object_1171.geometry}
            material={materials["Material_2.001"]}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1172"
            geometry={nodes.Object_1172.geometry}
            material={materials["Material_2.001"]}
            position={[17.06, -111.03, 97.23]}
          />
          <mesh
            name="Object_1173"
            geometry={nodes.Object_1173.geometry}
            material={materials["Material_2.001"]}
            position={[0, 17.66, 0]}
          />
        </group>
        <group name="pot" position={[0.89, 4.42, -6.52]} scale={0.29}>
          <group name="Plane493" position={[0, 1.92, 0]}>
            <mesh name="Plane497" geometry={nodes.Plane497.geometry} material={materials.stem} />
            <mesh
              name="Plane497_1"
              geometry={nodes.Plane497_1.geometry}
              material={materials["LEAF MID"]}
            />
            <mesh
              name="Plane497_2"
              geometry={nodes.Plane497_2.geometry}
              material={materials.leaf}
            />
            <mesh
              name="Plane497_3"
              geometry={nodes.Plane497_3.geometry}
              material={materials["LEAF DARK"]}
            />
          </group>
        </group>
        <group name="HeroObjectGroup" position={[0, 0.08, 0]} scale={0.01}>
          <mesh
            name="Succulent_02_low"
            geometry={nodes.Succulent_02_low.geometry}
            material={materials.stem}
            position={[-45.89, -20.28, -27.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={7.94}
          />
        </group>
        <group
          name="레이어_02"
          position={[-5.19, 3.71, -6.01]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh name="개체_1" geometry={nodes.개체_1.geometry} material={materials.재질_2} />
          <mesh name="개체_10" geometry={nodes.개체_10.geometry} material={materials.재질_2} />
          <mesh name="개체_11" geometry={nodes.개체_11.geometry} material={materials.재질_2} />
          <mesh name="개체_12" geometry={nodes.개체_12.geometry} material={materials.재질_2} />
          <mesh name="개체_13" geometry={nodes.개체_13.geometry} material={materials.재질_2} />
          <mesh name="개체_14" geometry={nodes.개체_14.geometry} material={materials.재질_2} />
          <mesh name="개체_15" geometry={nodes.개체_15.geometry} material={materials.재질_2} />
          <mesh name="개체_16" geometry={nodes.개체_16.geometry} material={materials.재질_2} />
          <mesh name="개체_17" geometry={nodes.개체_17.geometry} material={materials.재질_2} />
          <mesh name="개체_18" geometry={nodes.개체_18.geometry} material={materials.재질_2} />
          <mesh name="개체_19" geometry={nodes.개체_19.geometry} material={materials.재질_2} />
          <mesh name="개체_20" geometry={nodes.개체_20.geometry} material={materials.재질_2} />
          <mesh name="개체_21" geometry={nodes.개체_21.geometry} material={materials.재질_2} />
          <mesh name="개체_22" geometry={nodes.개체_22.geometry} material={materials.재질_2} />
          <mesh name="개체_23" geometry={nodes.개체_23.geometry} material={materials.재질_2} />
          <mesh name="개체_4" geometry={nodes.개체_4.geometry} material={materials.재질_2} />
          <mesh name="개체_5" geometry={nodes.개체_5.geometry} material={materials.재질_2} />
          <mesh name="개체_50" geometry={nodes.개체_50.geometry} material={materials.재질_2} />
          <mesh name="개체_8" geometry={nodes.개체_8.geometry} material={materials.재질_2} />
          <mesh name="개체_9" geometry={nodes.개체_9.geometry} material={materials.재질_2} />
        </group>
        <group
          name="레이어_01"
          position={[-5.19, 3.71, -6.01]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh name="개체_24" geometry={nodes.개체_24.geometry} material={materials.재질_2} />
          <mesh name="개체_25" geometry={nodes.개체_25.geometry} material={materials.재질_2} />
          <mesh name="개체_26" geometry={nodes.개체_26.geometry} material={materials.재질_2} />
          <mesh name="개체_27" geometry={nodes.개체_27.geometry} material={materials.재질_2} />
          <mesh name="개체_28" geometry={nodes.개체_28.geometry} material={materials.재질_2} />
          <mesh name="개체_29" geometry={nodes.개체_29.geometry} material={materials.재질_2} />
          <mesh name="개체_3" geometry={nodes.개체_3.geometry} material={materials.재질_2} />
          <mesh name="개체_30" geometry={nodes.개체_30.geometry} material={materials.재질_2} />
          <mesh name="개체_31" geometry={nodes.개체_31.geometry} material={materials.재질_2} />
          <mesh name="개체_32" geometry={nodes.개체_32.geometry} material={materials.재질_2} />
          <mesh name="개체_33" geometry={nodes.개체_33.geometry} material={materials.재질_2} />
          <mesh name="개체_34" geometry={nodes.개체_34.geometry} material={materials.재질_2} />
          <mesh name="개체_35" geometry={nodes.개체_35.geometry} material={materials.재질_2} />
          <mesh name="개체_36" geometry={nodes.개체_36.geometry} material={materials.재질_2} />
          <mesh name="개체_37" geometry={nodes.개체_37.geometry} material={materials.재질_2} />
          <mesh name="개체_38" geometry={nodes.개체_38.geometry} material={materials.재질_2} />
          <mesh name="개체_39" geometry={nodes.개체_39.geometry} material={materials.재질_2} />
          <mesh name="개체_40" geometry={nodes.개체_40.geometry} material={materials.재질_2} />
          <mesh name="개체_41" geometry={nodes.개체_41.geometry} material={materials.재질_2} />
          <mesh name="개체_42" geometry={nodes.개체_42.geometry} material={materials.재질_2} />
          <mesh name="개체_43" geometry={nodes.개체_43.geometry} material={materials.재질_2} />
          <mesh name="개체_44" geometry={nodes.개체_44.geometry} material={materials.재질_2} />
          <mesh name="개체_45" geometry={nodes.개체_45.geometry} material={materials.재질_2} />
          <mesh name="개체_46" geometry={nodes.개체_46.geometry} material={materials.재질_2} />
          <mesh name="개체_47" geometry={nodes.개체_47.geometry} material={materials.재질_2} />
          <mesh name="개체_48" geometry={nodes.개체_48.geometry} material={materials.재질_2} />
          <mesh name="개체_49" geometry={nodes.개체_49.geometry} material={materials.재질_2} />
          <mesh name="개체_6" geometry={nodes.개체_6.geometry} material={materials.재질_2} />
          <mesh name="개체_7" geometry={nodes.개체_7.geometry} material={materials.재질_2} />
        </group>
        <group
          name="레이어_02001"
          position={[-5.26, 3.25, -11.46]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_1001"
            geometry={nodes.개체_1001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_10001"
            geometry={nodes.개체_10001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_11001"
            geometry={nodes.개체_11001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_12001"
            geometry={nodes.개체_12001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_13001"
            geometry={nodes.개체_13001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_14001"
            geometry={nodes.개체_14001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_15001"
            geometry={nodes.개체_15001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_16001"
            geometry={nodes.개체_16001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_17001"
            geometry={nodes.개체_17001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_18001"
            geometry={nodes.개체_18001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_19001"
            geometry={nodes.개체_19001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_20001"
            geometry={nodes.개체_20001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_21001"
            geometry={nodes.개체_21001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_22001"
            geometry={nodes.개체_22001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_23001"
            geometry={nodes.개체_23001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_4001"
            geometry={nodes.개체_4001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_5001"
            geometry={nodes.개체_5001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_50001"
            geometry={nodes.개체_50001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_8001"
            geometry={nodes.개체_8001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_9001"
            geometry={nodes.개체_9001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group
          name="레이어_01001"
          position={[-5.26, 3.25, -11.46]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_24001"
            geometry={nodes.개체_24001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_25001"
            geometry={nodes.개체_25001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_26001"
            geometry={nodes.개체_26001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_27001"
            geometry={nodes.개체_27001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_28001"
            geometry={nodes.개체_28001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_29001"
            geometry={nodes.개체_29001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_3001"
            geometry={nodes.개체_3001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_30001"
            geometry={nodes.개체_30001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_31001"
            geometry={nodes.개체_31001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_32001"
            geometry={nodes.개체_32001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_33001"
            geometry={nodes.개체_33001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_34001"
            geometry={nodes.개체_34001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_35001"
            geometry={nodes.개체_35001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_36001"
            geometry={nodes.개체_36001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_37001"
            geometry={nodes.개체_37001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_38001"
            geometry={nodes.개체_38001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_39001"
            geometry={nodes.개체_39001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_40001"
            geometry={nodes.개체_40001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_41001"
            geometry={nodes.개체_41001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_42001"
            geometry={nodes.개체_42001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_43001"
            geometry={nodes.개체_43001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_44001"
            geometry={nodes.개체_44001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_45001"
            geometry={nodes.개체_45001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_46001"
            geometry={nodes.개체_46001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_47001"
            geometry={nodes.개체_47001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_48001"
            geometry={nodes.개체_48001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_49001"
            geometry={nodes.개체_49001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_6001"
            geometry={nodes.개체_6001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_7001"
            geometry={nodes.개체_7001.geometry}
            material={materials.재질_2}
            position={[-2442.08, 629.73, -3707.84]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group name="MINI_PLANT02" position={[-3.73, 2.03, 0.84]} scale={0}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.Material} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.green_15} />
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials["LEAF DARK"]} />
          <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials.Glass} />
          <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials.ground2} />
          <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials.ground3} />
        </group>
        <group name="MINI_PLANT01" position={[2.89, -1.36, -40.25]} scale={0}>
          <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials.Leaves_06p} />
          <mesh
            name="Mesh001_1"
            geometry={nodes.Mesh001_1.geometry}
            material={materials.Leaves_07p}
          />
          <mesh name="Mesh001_2" geometry={nodes.Mesh001_2.geometry} material={materials.Glass} />
          <mesh name="Mesh001_3" geometry={nodes.Mesh001_3.geometry} material={materials.ground2} />
          <mesh name="Mesh001_4" geometry={nodes.Mesh001_4.geometry} material={materials.ground3} />
        </group>
        <mesh
          name="Plant_03"
          geometry={nodes.Plant_03.geometry}
          material={materials.Plant_03}
          position={[-1.2, 2.09, -45.15]}
          scale={0.2}
        />
        <mesh
          name="Plant_04"
          geometry={nodes.Plant_04.geometry}
          material={materials.Plant_04}
          position={[-4.48, -6.31, -61.67]}
          scale={0.42}
        />
        <mesh
          name="Plant_02"
          geometry={nodes.Plant_02.geometry}
          material={materials.Plant_02}
          position={[2.01, -0.2, 10.94]}
          scale={0.06}
        />
        <mesh
          name="Sucu_longM_01"
          geometry={nodes.Sucu_longM_01.geometry}
          material={materials.stem}
          position={[3.04, 1.56, -41.39]}
          rotation={[1.59, 0.11, 2.74]}
          scale={10.65}
        />
        <mesh
          name="Sucu_ShortS_01"
          geometry={nodes.Sucu_ShortS_01.geometry}
          material={materials.Plant_04}
          position={[3.1, 1.57, -41.86]}
          rotation={[1.48, -0.05, -0.28]}
          scale={[7.36, 7.36, 6.84]}
        />
        <mesh
          name="Sucu_ShortL_02"
          geometry={nodes.Sucu_ShortL_02.geometry}
          material={materials.stem}
          position={[2.79, 1.57, -41.68]}
          rotation={[1.54, 0.14, -2.18]}
          scale={[10.62, 10.62, 9.67]}
        />
        <mesh
          name="Sucu_longL_02"
          geometry={nodes.Sucu_longL_02.geometry}
          material={materials.stem}
          position={[3.21, 1.59, -41.59]}
          rotation={[1.51, -0.06, 0.01]}
          scale={[12.95, 12.95, 12.37]}
        />
        <group name="Pot" position={[2.97, 1.54, -41.61]} rotation={[0, 0.28, 0]} scale={12.95}>
          <mesh
            name="Circle001"
            geometry={nodes.Circle001.geometry}
            material={materials.Material}
          />
          <mesh
            name="Circle001_1"
            geometry={nodes.Circle001_1.geometry}
            material={materials.Ground}
          />
          <mesh
            name="Circle001_2"
            geometry={nodes.Circle001_2.geometry}
            material={materials.GreenStones}
          />
        </group>
        <group
          name="BIG_PLANT001"
          position={[-0.75, 0.58, -21.11]}
          rotation={[Math.PI, -0.09, Math.PI]}
          scale={0}
        >
          <mesh name="Mesh016" geometry={nodes.Mesh016.geometry} material={materials.Leaves_03b} />
          <mesh
            name="Mesh016_1"
            geometry={nodes.Mesh016_1.geometry}
            material={materials.Leaves_04b}
          />
          <mesh
            name="Mesh016_2"
            geometry={nodes.Mesh016_2.geometry}
            material={materials.green_16}
          />
          <mesh
            name="Mesh016_3"
            geometry={nodes.Mesh016_3.geometry}
            material={materials.Leaves_02g}
          />
          <mesh
            name="Mesh016_4"
            geometry={nodes.Mesh016_4.geometry}
            material={materials.green_15}
          />
          <mesh
            name="Mesh016_5"
            geometry={nodes.Mesh016_5.geometry}
            material={materials.Leaves_01g}
          />
          <mesh name="Mesh016_6" geometry={nodes.Mesh016_6.geometry} material={materials.wood001} />
          <mesh name="Mesh016_7" geometry={nodes.Mesh016_7.geometry} material={materials.ground} />
        </group>
        <mesh
          name="Plant_03001"
          geometry={nodes.Plant_03001.geometry}
          material={materials.Plant_03}
          position={[9.56, -2.26, -23.29]}
          scale={0.2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/sunyena-draco.gltf");
