/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Akinain(props) {
  const { nodes, materials } = useGLTF("/akinain.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-2.08, -0.98, -16.74]} rotation={[Math.PI / 2, 0, 2.44]} scale={0.01}>
        <group position={[-106.1, 8.8, 3.51]}>
          <group position={[106.1, -70.4, -50.83]}>
            <mesh
              geometry={nodes["36days_b001"].geometry}
              material={materials["Plastic Polycarbonate #1"]}
            />
          </group>
          <group position={[-2565.14, 2226.26, -586.17]} rotation={[-1.97, -0.47, 2.74]}>
            <mesh
              geometry={nodes["36days_b002"].geometry}
              material={materials["Plastic Polycarbonate #1"]}
            />
          </group>
          <group position={[-4214.34, 4716.14, -429.08]} rotation={[-1.97, -0.47, 2.74]}>
            <mesh
              geometry={nodes["36days_b004"].geometry}
              material={materials["Plastic Polycarbonate #1"]}
            />
          </group>
          <mesh
            geometry={nodes.belt_b001.geometry}
            material={materials["Cloth Weave Black 1mm #1"]}
          />
          <mesh
            geometry={nodes.belt_b002.geometry}
            material={materials["Cloth Weave Black 1mm #1"]}
            position={[-2525.06, 2338.49, -518.37]}
            rotation={[-1.97, -0.47, 2.74]}
          />
          <mesh
            geometry={nodes.belt_b003.geometry}
            material={materials["Cloth Weave Black 1mm #1"]}
            position={[-4174.26, 4828.36, -361.29]}
            rotation={[-1.97, -0.47, 2.74]}
          />
        </group>
      </group>
      <group position={[0.11, -1.5, -9.53]} rotation={[0.9, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Object_1.geometry}
          material={materials["Material_2.001"]}
          position={[0, 9.8, -12.32]}
        />
        <mesh
          geometry={nodes.Object_1002.geometry}
          material={materials["Material_2.001"]}
          position={[0, -115.64, -112.07]}
        />
        <mesh
          geometry={nodes.Object_1004.geometry}
          material={materials["Material_2.001"]}
          position={[0, -233.54, -205.84]}
        />
        <mesh
          geometry={nodes.Object_1006.geometry}
          material={materials["Material_2.001"]}
          position={[0, -358.98, -305.6]}
        />
        <mesh
          geometry={nodes.Object_1008.geometry}
          material={materials["Material_2.001"]}
          position={[0, -967.23, -789.32]}
        />
        <mesh
          geometry={nodes.Object_1010.geometry}
          material={materials["Material_2.001"]}
          position={[-341.43, -1070.08, -1175.65]}
        />
        <mesh
          geometry={nodes.Object_1012.geometry}
          material={materials["Material_2.001"]}
          position={[0, -1210.57, -982.84]}
        />
        <mesh
          geometry={nodes.Object_1014.geometry}
          material={materials["Material_2.001"]}
          position={[0, -1336.01, -1082.6]}
        />
        <mesh
          geometry={nodes.Object_1016.geometry}
          material={materials["Material_2.001"]}
          position={[0, -2268.14, -1823.9]}
        />
        <mesh
          geometry={nodes.Object_1018.geometry}
          material={materials["Material_2.001"]}
          position={[0, -2393.58, -1923.65]}
        />
        <mesh
          geometry={nodes.Object_1020.geometry}
          material={materials["Material_2.001"]}
          position={[177.71, -2745.87, -2239.17]}
        />
        <mesh
          geometry={nodes.Object_1022.geometry}
          material={materials["Material_2.001"]}
          position={[0, -2636.92, -2117.17]}
        />
        <mesh
          geometry={nodes.Object_1024.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3568.5, -2858.03]}
        />
        <mesh
          geometry={nodes.Object_1026.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3693.93, -2957.79]}
        />
        <mesh
          geometry={nodes.Object_1028.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3811.84, -3051.56]}
        />
        <mesh
          geometry={nodes.Object_1030.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3937.27, -3151.31]}
        />
        <mesh
          geometry={nodes.Object_1032.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5159.6, -4123.39]}
        />
        <mesh
          geometry={nodes.Object_1034.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5285.03, -4223.15]}
        />
        <mesh
          geometry={nodes.Object_1036.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5402.93, -4316.91]}
        />
        <mesh
          geometry={nodes.Object_1038.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5528.37, -4416.67]}
        />
        <mesh
          geometry={nodes.Object_1040.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5935, -4740.05]}
        />
        <mesh
          geometry={nodes.Object_1042.geometry}
          material={materials["Material_2.001"]}
          position={[0, -6060.44, -4839.81]}
        />
        <mesh
          geometry={nodes.Object_1044.geometry}
          material={materials["Material_2.001"]}
          position={[0, -6178.34, -4933.57]}
        />
        <mesh
          geometry={nodes.Object_1046.geometry}
          material={materials["Material_2.001"]}
          position={[0, -6303.78, -5033.33]}
        />
      </group>
      <group position={[0.11, -1.5, -10.18]} rotation={[0.9, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Object_1001.geometry}
          material={materials["Material_2.001"]}
          position={[0, 9.8, -12.32]}
        />
        <mesh
          geometry={nodes.Object_1003.geometry}
          material={materials["Material_2.001"]}
          position={[0, -115.64, -112.07]}
        />
        <mesh
          geometry={nodes.Object_1005.geometry}
          material={materials["Material_2.001"]}
          position={[0, -233.54, -205.84]}
        />
        <mesh
          geometry={nodes.Object_1007.geometry}
          material={materials["Material_2.001"]}
          position={[0, -358.98, -305.6]}
        />
        <mesh
          geometry={nodes.Object_1009.geometry}
          material={materials["Material_2.001"]}
          position={[0, -967.23, -789.32]}
        />
        <mesh
          geometry={nodes.Object_1011.geometry}
          material={materials["Material_2.001"]}
          position={[0, -1092.67, -889.08]}
        />
        <mesh
          geometry={nodes.Object_1013.geometry}
          material={materials["Material_2.001"]}
          position={[0, -1210.57, -982.84]}
        />
        <mesh
          geometry={nodes.Object_1015.geometry}
          material={materials["Material_2.001"]}
          position={[0, -1336.01, -1082.6]}
        />
        <mesh
          geometry={nodes.Object_1017.geometry}
          material={materials["Material_2.001"]}
          position={[0, -2268.14, -1823.9]}
        />
        <mesh
          geometry={nodes.Object_1019.geometry}
          material={materials["Material_2.001"]}
          position={[369.14, -2426.41, -2183.08]}
        />
        <mesh
          geometry={nodes.Object_1021.geometry}
          material={materials["Material_2.001"]}
          position={[0, -2511.48, -2017.42]}
        />
        <mesh
          geometry={nodes.Object_1023.geometry}
          material={materials["Material_2.001"]}
          position={[0, -2636.92, -2117.17]}
        />
        <mesh
          geometry={nodes.Object_1025.geometry}
          material={materials["Material_2.001"]}
          position={[-217.96, -3657.04, -2987.17]}
        />
        <mesh
          geometry={nodes.Object_1027.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3693.93, -2957.79]}
        />
        <mesh
          geometry={nodes.Object_1029.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3811.84, -3051.56]}
        />
        <mesh
          geometry={nodes.Object_1031.geometry}
          material={materials["Material_2.001"]}
          position={[0, -3937.27, -3151.31]}
        />
        <mesh
          geometry={nodes.Object_1033.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5159.6, -4123.39]}
        />
        <mesh
          geometry={nodes.Object_1035.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5285.03, -4223.15]}
        />
        <mesh
          geometry={nodes.Object_1037.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5402.93, -4316.91]}
        />
        <mesh
          geometry={nodes.Object_1039.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5528.37, -4416.67]}
        />
        <mesh
          geometry={nodes.Object_1041.geometry}
          material={materials["Material_2.001"]}
          position={[0, -5935, -4740.05]}
        />
        <mesh
          geometry={nodes.Object_1043.geometry}
          material={materials["Material_2.001"]}
          position={[0, -6060.44, -4839.81]}
        />
        <mesh
          geometry={nodes.Object_1045.geometry}
          material={materials["Material_2.001"]}
          position={[0, -6178.34, -4933.57]}
        />
        <mesh
          geometry={nodes.Object_1047.geometry}
          material={materials["Material_2.001"]}
          position={[0, -6303.78, -5033.33]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh
          geometry={nodes.개체_52.geometry}
          material={materials["재질_2.001"]}
          position={[-17984.97, -16936.63, -11.94]}
          rotation={[0.52, 0, 0]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_52001.geometry}
          material={materials["재질_2.001"]}
          position={[-19538.04, -39932.13, -11.94]}
          rotation={[0.45, 0.29, 0.54]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_52002.geometry}
          material={materials["재질_2.001"]}
          position={[-14677.32, -53981.52, -11.94]}
          rotation={[0.45, 0.29, 0.54]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_52003.geometry}
          material={materials["재질_2.001"]}
          position={[-25871.45, -56812.21, -11.94]}
          rotation={[0.48, -0.23, -0.41]}
          scale={-23.67}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh
          geometry={nodes.개체_51.geometry}
          material={materials["재질_2.001"]}
          position={[-17984.97, -16936.63, -11.94]}
          rotation={[0.52, 0, 0]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_51001.geometry}
          material={materials["재질_2.001"]}
          position={[-19538.04, -39932.13, -11.94]}
          rotation={[0.45, 0.29, 0.54]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_51002.geometry}
          material={materials["재질_2.001"]}
          position={[-14677.32, -53981.52, -11.94]}
          rotation={[0.45, 0.29, 0.54]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_51003.geometry}
          material={materials["재질_2.001"]}
          position={[-25871.45, -56812.21, -11.94]}
          rotation={[0.48, -0.23, -0.41]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_53.geometry}
          material={materials["재질_2.001"]}
          position={[-17984.97, -16936.63, -11.94]}
          rotation={[0.52, 0, 0]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_53001.geometry}
          material={materials["재질_2.001"]}
          position={[-19538.04, -39932.13, -11.94]}
          rotation={[0.45, 0.29, 0.54]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_53002.geometry}
          material={materials["재질_2.001"]}
          position={[-13776.64, -54110.19, -11.94]}
          rotation={[0.45, 0.29, 0.54]}
          scale={-23.67}
        />
        <mesh
          geometry={nodes.개체_53003.geometry}
          material={materials["재질_2.001"]}
          position={[-25871.45, -56812.21, -11.94]}
          rotation={[0.48, -0.23, -0.41]}
          scale={-23.67}
        />
      </group>
      <group position={[0.89, -1.38, -14.9]} rotation={[-2.3, -0.79, -1.99]} scale={4.37}>
        <mesh geometry={nodes.Mesh.geometry} material={materials["Material #2 Slot #1"]} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials["3M_6200_RUBBER"]} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials["3M_6200_BUCKLE"]} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials["3M_6200_PLASTIC GREY"]} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials["3M_FILTER SEAL"]} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials["3M_6200_ELASTIC"]} />
      </group>
      <group position={[0.99, -1.46, -14.83]} rotation={[-2.3, -0.79, -1.99]} scale={4.37}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials["3M_FILTER_FABRIC"]} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials["3M_FILTER SEAL"]} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials["3M_FILTER_GREY"]} />
      </group>
      <mesh
        geometry={nodes.Object_1261.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1263.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1264.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1284.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1285.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1286.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <group position={[-1.36, -0.11, -33.82]} rotation={[1.4, 0.46, 0.55]} scale={4.37}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials["Material #2 Slot #1"]} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials["3M_6200_RUBBER"]} />
        <mesh geometry={nodes.Mesh002_2.geometry} material={materials["3M_6200_BUCKLE"]} />
        <mesh geometry={nodes.Mesh002_3.geometry} material={materials["3M_6200_PLASTIC GREY"]} />
        <mesh geometry={nodes.Mesh002_4.geometry} material={materials["3M_FILTER SEAL"]} />
        <mesh geometry={nodes.Mesh002_5.geometry} material={materials["3M_6200_ELASTIC"]} />
      </group>
      <group position={[-1.42, 0.01, -33.84]} rotation={[1.4, 0.46, 0.55]} scale={4.37}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials["default"]} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials["3M_FILTER SEAL"]} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials["3M_FILTER_GREY"]} />
      </group>
      <mesh
        geometry={nodes.Object_1296.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1298.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1299.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1318.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1319.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
      <mesh
        geometry={nodes.Object_1320.geometry}
        material={materials.Material_2}
        position={[292.62, -459.14, -1500.17]}
      />
    </group>
  );
}

useGLTF.preload("/akinain.gltf");
