/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Dipak(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/dipak.gltf");
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera" position={[0, 0, -0.16]} rotation={[Math.PI / 2, 0, 0]} />
        <group
          name="Camera001"
          position={[0, 0, -0.16]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.87}
        />
        <group name="기본값" rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <mesh name="개체_1" geometry={nodes.개체_1.geometry} material={materials["재질_2.001"]} />
        </group>
        <group name="레이어_01002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_1001"
            geometry={nodes.개체_1001.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_1002"
            geometry={nodes.개체_1002.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_30"
            geometry={nodes.개체_30.geometry}
            material={materials["Material.010"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_30001"
            geometry={nodes.개체_30001.geometry}
            material={materials["Material.010"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_31"
            geometry={nodes.개체_31.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_31001"
            geometry={nodes.개체_31001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_06002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_108"
            geometry={nodes.개체_108.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_108001"
            geometry={nodes.개체_108001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_125"
            geometry={nodes.개체_125.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_125001"
            geometry={nodes.개체_125001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_3"
            geometry={nodes.개체_3.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_3001"
            geometry={nodes.개체_3001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_82"
            geometry={nodes.개체_82.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_82001"
            geometry={nodes.개체_82001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_95"
            geometry={nodes.개체_95.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_95001"
            geometry={nodes.개체_95001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_03002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_10"
            geometry={nodes.개체_10.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_10001"
            geometry={nodes.개체_10001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_100"
            geometry={nodes.개체_100.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_100001"
            geometry={nodes.개체_100001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_103"
            geometry={nodes.개체_103.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_103001"
            geometry={nodes.개체_103001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_107"
            geometry={nodes.개체_107.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_107001"
            geometry={nodes.개체_107001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_11"
            geometry={nodes.개체_11.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_11001"
            geometry={nodes.개체_11001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_111"
            geometry={nodes.개체_111.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_111001"
            geometry={nodes.개체_111001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_112"
            geometry={nodes.개체_112.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_112001"
            geometry={nodes.개체_112001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_113"
            geometry={nodes.개체_113.geometry}
            material={materials["Material.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_113001"
            geometry={nodes.개체_113001.geometry}
            material={materials["Material.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_116"
            geometry={nodes.개체_116.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_116001"
            geometry={nodes.개체_116001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_117"
            geometry={nodes.개체_117.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_117001"
            geometry={nodes.개체_117001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_12"
            geometry={nodes.개체_12.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_12001"
            geometry={nodes.개체_12001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_120"
            geometry={nodes.개체_120.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_120001"
            geometry={nodes.개체_120001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_121"
            geometry={nodes.개체_121.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_121001"
            geometry={nodes.개체_121001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_122"
            geometry={nodes.개체_122.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_122001"
            geometry={nodes.개체_122001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_126"
            geometry={nodes.개체_126.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_126001"
            geometry={nodes.개체_126001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_13"
            geometry={nodes.개체_13.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_13001"
            geometry={nodes.개체_13001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_34"
            geometry={nodes.개체_34.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_34001"
            geometry={nodes.개체_34001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_4"
            geometry={nodes.개체_4.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_4001"
            geometry={nodes.개체_4001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_45"
            geometry={nodes.개체_45.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_45001"
            geometry={nodes.개체_45001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_5"
            geometry={nodes.개체_5.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_5001"
            geometry={nodes.개체_5001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_56"
            geometry={nodes.개체_56.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_56001"
            geometry={nodes.개체_56001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_6"
            geometry={nodes.개체_6.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_6001"
            geometry={nodes.개체_6001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_7"
            geometry={nodes.개체_7.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_7001"
            geometry={nodes.개체_7001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_77"
            geometry={nodes.개체_77.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_77001"
            geometry={nodes.개체_77001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_8"
            geometry={nodes.개체_8.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_8001"
            geometry={nodes.개체_8001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_81"
            geometry={nodes.개체_81.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_81001"
            geometry={nodes.개체_81001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_85"
            geometry={nodes.개체_85.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_85001"
            geometry={nodes.개체_85001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_86"
            geometry={nodes.개체_86.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_86001"
            geometry={nodes.개체_86001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_87"
            geometry={nodes.개체_87.geometry}
            material={materials["Material.009"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_87001"
            geometry={nodes.개체_87001.geometry}
            material={materials["Material.009"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_9"
            geometry={nodes.개체_9.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_9001"
            geometry={nodes.개체_9001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_90"
            geometry={nodes.개체_90.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_90001"
            geometry={nodes.개체_90001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_94"
            geometry={nodes.개체_94.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_94001"
            geometry={nodes.개체_94001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_98"
            geometry={nodes.개체_98.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_98001"
            geometry={nodes.개체_98001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_99"
            geometry={nodes.개체_99.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_99001"
            geometry={nodes.개체_99001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_05002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_110"
            geometry={nodes.개체_110.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_110001"
            geometry={nodes.개체_110001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_123"
            geometry={nodes.개체_123.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_123001"
            geometry={nodes.개체_123001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_14"
            geometry={nodes.개체_14.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_14001"
            geometry={nodes.개체_14001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_15"
            geometry={nodes.개체_15.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_15001"
            geometry={nodes.개체_15001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_16"
            geometry={nodes.개체_16.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_16001"
            geometry={nodes.개체_16001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_17"
            geometry={nodes.개체_17.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_17001"
            geometry={nodes.개체_17001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_18"
            geometry={nodes.개체_18.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_18001"
            geometry={nodes.개체_18001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_19"
            geometry={nodes.개체_19.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_19001"
            geometry={nodes.개체_19001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_20"
            geometry={nodes.개체_20.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_20001"
            geometry={nodes.개체_20001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_21"
            geometry={nodes.개체_21.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_21001"
            geometry={nodes.개체_21001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_22"
            geometry={nodes.개체_22.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_22001"
            geometry={nodes.개체_22001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_23"
            geometry={nodes.개체_23.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_23001"
            geometry={nodes.개체_23001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_24"
            geometry={nodes.개체_24.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_24001"
            geometry={nodes.개체_24001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_25"
            geometry={nodes.개체_25.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_25001"
            geometry={nodes.개체_25001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_26"
            geometry={nodes.개체_26.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_26001"
            geometry={nodes.개체_26001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_27"
            geometry={nodes.개체_27.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_27001"
            geometry={nodes.개체_27001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_28"
            geometry={nodes.개체_28.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_28001"
            geometry={nodes.개체_28001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_29"
            geometry={nodes.개체_29.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_29001"
            geometry={nodes.개체_29001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_32"
            geometry={nodes.개체_32.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_32001"
            geometry={nodes.개체_32001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_33"
            geometry={nodes.개체_33.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_33001"
            geometry={nodes.개체_33001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_35"
            geometry={nodes.개체_35.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_35001"
            geometry={nodes.개체_35001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_36"
            geometry={nodes.개체_36.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_36001"
            geometry={nodes.개체_36001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_37"
            geometry={nodes.개체_37.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_37001"
            geometry={nodes.개체_37001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_38"
            geometry={nodes.개체_38.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_38001"
            geometry={nodes.개체_38001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_39"
            geometry={nodes.개체_39.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_39001"
            geometry={nodes.개체_39001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_40"
            geometry={nodes.개체_40.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_40001"
            geometry={nodes.개체_40001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_41"
            geometry={nodes.개체_41.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_41001"
            geometry={nodes.개체_41001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_42"
            geometry={nodes.개체_42.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_42001"
            geometry={nodes.개체_42001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_43"
            geometry={nodes.개체_43.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_43001"
            geometry={nodes.개체_43001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_46"
            geometry={nodes.개체_46.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_46001"
            geometry={nodes.개체_46001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_47"
            geometry={nodes.개체_47.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_47001"
            geometry={nodes.개체_47001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_48"
            geometry={nodes.개체_48.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_48001"
            geometry={nodes.개체_48001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_49"
            geometry={nodes.개체_49.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_49001"
            geometry={nodes.개체_49001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_50"
            geometry={nodes.개체_50.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_50001"
            geometry={nodes.개체_50001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_51"
            geometry={nodes.개체_51.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_51001"
            geometry={nodes.개체_51001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_52"
            geometry={nodes.개체_52.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_52001"
            geometry={nodes.개체_52001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_53"
            geometry={nodes.개체_53.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_53001"
            geometry={nodes.개체_53001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_54"
            geometry={nodes.개체_54.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_54001"
            geometry={nodes.개체_54001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_57"
            geometry={nodes.개체_57.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_57001"
            geometry={nodes.개체_57001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_58"
            geometry={nodes.개체_58.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_58001"
            geometry={nodes.개체_58001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_59"
            geometry={nodes.개체_59.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_59001"
            geometry={nodes.개체_59001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_60"
            geometry={nodes.개체_60.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_60001"
            geometry={nodes.개체_60001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_61"
            geometry={nodes.개체_61.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_61001"
            geometry={nodes.개체_61001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_62"
            geometry={nodes.개체_62.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_62001"
            geometry={nodes.개체_62001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_63"
            geometry={nodes.개체_63.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_63001"
            geometry={nodes.개체_63001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_64"
            geometry={nodes.개체_64.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_64001"
            geometry={nodes.개체_64001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_65"
            geometry={nodes.개체_65.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_65001"
            geometry={nodes.개체_65001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_68"
            geometry={nodes.개체_68.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_68001"
            geometry={nodes.개체_68001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_69"
            geometry={nodes.개체_69.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_69001"
            geometry={nodes.개체_69001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_70"
            geometry={nodes.개체_70.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_70001"
            geometry={nodes.개체_70001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_71"
            geometry={nodes.개체_71.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_71001"
            geometry={nodes.개체_71001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_72"
            geometry={nodes.개체_72.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_72001"
            geometry={nodes.개체_72001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_73"
            geometry={nodes.개체_73.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_73001"
            geometry={nodes.개체_73001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_74"
            geometry={nodes.개체_74.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_74001"
            geometry={nodes.개체_74001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_75"
            geometry={nodes.개체_75.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_75001"
            geometry={nodes.개체_75001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_76"
            geometry={nodes.개체_76.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_76001"
            geometry={nodes.개체_76001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_84"
            geometry={nodes.개체_84.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_84001"
            geometry={nodes.개체_84001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_97"
            geometry={nodes.개체_97.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_97001"
            geometry={nodes.개체_97001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_08002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_44"
            geometry={nodes.개체_44.geometry}
            material={materials["Material.008"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_44001"
            geometry={nodes.개체_44001.geometry}
            material={materials["Material.008"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_55"
            geometry={nodes.개체_55.geometry}
            material={materials["Material.008"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_55001"
            geometry={nodes.개체_55001.geometry}
            material={materials["Material.008"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_66"
            geometry={nodes.개체_66.geometry}
            material={materials["Material.008"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_66001"
            geometry={nodes.개체_66001.geometry}
            material={materials["Material.008"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_67"
            geometry={nodes.개체_67.geometry}
            material={materials["Material.008"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_67001"
            geometry={nodes.개체_67001.geometry}
            material={materials["Material.008"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_02002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_104"
            geometry={nodes.개체_104.geometry}
            material={materials["Material.010"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_104001"
            geometry={nodes.개체_104001.geometry}
            material={materials["Material.010"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_105"
            geometry={nodes.개체_105.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_105001"
            geometry={nodes.개체_105001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_106"
            geometry={nodes.개체_106.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_106001"
            geometry={nodes.개체_106001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_127"
            geometry={nodes.개체_127.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_127001"
            geometry={nodes.개체_127001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_128"
            geometry={nodes.개체_128.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_128001"
            geometry={nodes.개체_128001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_129"
            geometry={nodes.개체_129.geometry}
            material={materials["Material.010"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_129001"
            geometry={nodes.개체_129001.geometry}
            material={materials["Material.010"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_78"
            geometry={nodes.개체_78.geometry}
            material={materials["Material.010"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_78001"
            geometry={nodes.개체_78001.geometry}
            material={materials["Material.010"]}
            position={[168.2, -2304.03, -166.14]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_79"
            geometry={nodes.개체_79.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_79001"
            geometry={nodes.개체_79001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_80"
            geometry={nodes.개체_80.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_80001"
            geometry={nodes.개체_80001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_91"
            geometry={nodes.개체_91.geometry}
            material={materials["Material.010"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_91001"
            geometry={nodes.개체_91001.geometry}
            material={materials["Material.010"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_92"
            geometry={nodes.개체_92.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_92001"
            geometry={nodes.개체_92001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_93"
            geometry={nodes.개체_93.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_93001"
            geometry={nodes.개체_93001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_04002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_109"
            geometry={nodes.개체_109.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_109001"
            geometry={nodes.개체_109001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_124"
            geometry={nodes.개체_124.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_124001"
            geometry={nodes.개체_124001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_83"
            geometry={nodes.개체_83.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_83001"
            geometry={nodes.개체_83001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_96"
            geometry={nodes.개체_96.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_96001"
            geometry={nodes.개체_96001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="레이어_07002" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <mesh
            name="개체_101"
            geometry={nodes.개체_101.geometry}
            material={materials["Material.006"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_101001"
            geometry={nodes.개체_101001.geometry}
            material={materials["Material.006"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_102"
            geometry={nodes.개체_102.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_102001"
            geometry={nodes.개체_102001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_114"
            geometry={nodes.개체_114.geometry}
            material={materials["Material.006"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_114001"
            geometry={nodes.개체_114001.geometry}
            material={materials["Material.006"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_115"
            geometry={nodes.개체_115.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_115001"
            geometry={nodes.개체_115001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_118"
            geometry={nodes.개체_118.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_118001"
            geometry={nodes.개체_118001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_119"
            geometry={nodes.개체_119.geometry}
            material={materials["Material.006"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_119001"
            geometry={nodes.개체_119001.geometry}
            material={materials["Material.006"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_88"
            geometry={nodes.개체_88.geometry}
            material={materials["Material.006"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_88001"
            geometry={nodes.개체_88001.geometry}
            material={materials["Material.006"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
          <mesh
            name="개체_89"
            geometry={nodes.개체_89.geometry}
            material={materials["재질_2.004"]}
            position={[-99.76, -653.87, 3.66]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={0.63}
          />
          <mesh
            name="개체_89001"
            geometry={nodes.개체_89001.geometry}
            material={materials["재질_2.004"]}
            position={[94.41, -2304.03, -163.07]}
            rotation={[-1.22, -0.66, 2.02]}
            scale={1.86}
          />
        </group>
        <group name="기본값001" rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
          <mesh
            name="개체_1003"
            geometry={nodes.개체_1003.geometry}
            material={materials["재질_2.005"]}
            position={[305.69, -2217.09, 335.12]}
            scale={13.8}
          />
          <mesh
            name="개체_1004"
            geometry={nodes.개체_1004.geometry}
            material={materials["재질_2.005"]}
            position={[305.69, -2285.46, 335.12]}
            scale={13.8}
          />
          <mesh
            name="개체_1005"
            geometry={nodes.개체_1005.geometry}
            material={materials["재질_2.005"]}
            position={[305.69, -2353.4, 335.12]}
            scale={13.8}
          />
          <mesh
            name="개체_1006"
            geometry={nodes.개체_1006.geometry}
            material={materials["재질_2.005"]}
            position={[305.69, -2421.77, 335.12]}
            scale={13.8}
          />
          <mesh
            name="개체_1007"
            geometry={nodes.개체_1007.geometry}
            material={materials["재질_2.005"]}
            position={[302.1, -2491.9, 345.89]}
            scale={13.8}
          />
          <mesh
            name="개체_1008"
            geometry={nodes.개체_1008.geometry}
            material={materials["재질_2.005"]}
            position={[302.1, -2560.26, 345.89]}
            scale={13.8}
          />
          <mesh
            name="개체_1009"
            geometry={nodes.개체_1009.geometry}
            material={materials["재질_2.005"]}
            position={[302.1, -2648.02, 345.89]}
            scale={13.8}
          />
          <mesh
            name="개체_1010"
            geometry={nodes.개체_1010.geometry}
            material={materials["재질_2.005"]}
            position={[302.1, -2716.38, 345.89]}
            scale={13.8}
          />
          <mesh
            name="개체_1011"
            geometry={nodes.개체_1011.geometry}
            material={materials["재질_2.005"]}
            position={[399.69, -2349.44, -123.33]}
            scale={6.34}
          />
          <mesh
            name="개체_1012"
            geometry={nodes.개체_1012.geometry}
            material={materials["재질_2.005"]}
            position={[399.69, -2380.83, -123.33]}
            scale={6.34}
          />
          <mesh
            name="개체_1013"
            geometry={nodes.개체_1013.geometry}
            material={materials["재질_2.005"]}
            position={[399.69, -2412.02, -123.33]}
            scale={6.34}
          />
          <mesh
            name="개체_1014"
            geometry={nodes.개체_1014.geometry}
            material={materials["재질_2.005"]}
            position={[399.69, -2443.41, -123.33]}
            scale={6.34}
          />
          <mesh
            name="개체_1015"
            geometry={nodes.개체_1015.geometry}
            material={materials["재질_2.005"]}
            position={[398.05, -2475.61, -118.39]}
            scale={6.34}
          />
          <mesh
            name="개체_1016"
            geometry={nodes.개체_1016.geometry}
            material={materials["재질_2.005"]}
            position={[398.05, -2506.99, -118.39]}
            scale={6.34}
          />
          <mesh
            name="개체_1017"
            geometry={nodes.개체_1017.geometry}
            material={materials["재질_2.005"]}
            position={[46.84, -735.64, 84.69]}
            rotation={[0, 1.08, 0]}
            scale={3.15}
          />
          <mesh
            name="개체_1018"
            geometry={nodes.개체_1018.geometry}
            material={materials["재질_2.005"]}
            position={[46.84, -751.23, 84.69]}
            rotation={[0, 1.27, 0]}
            scale={3.15}
          />
          <mesh
            name="개체_1019"
            geometry={nodes.개체_1019.geometry}
            material={materials["재질_2.005"]}
            position={[46.84, -771.23, 84.69]}
            rotation={[0, 1.5, 0]}
            scale={3.15}
          />
          <mesh
            name="개체_1020"
            geometry={nodes.개체_1020.geometry}
            material={materials["재질_2.005"]}
            position={[46.84, -786.82, 84.69]}
            rotation={[-Math.PI, 1.45, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1021"
            geometry={nodes.개체_1021.geometry}
            material={materials["재질_2.005"]}
            position={[-4.22, -916.13, 111.58]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1022"
            geometry={nodes.개체_1022.geometry}
            material={materials["재질_2.005"]}
            position={[-4.22, -931.71, 111.58]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1023"
            geometry={nodes.개체_1023.geometry}
            material={materials["재질_2.005"]}
            position={[-4.22, -947.21, 111.58]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1024"
            geometry={nodes.개체_1024.geometry}
            material={materials["재질_2.005"]}
            position={[-4.22, -962.79, 111.58]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1025"
            geometry={nodes.개체_1025.geometry}
            material={materials["재질_2.005"]}
            position={[-1.96, -978.78, 110.33]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1026"
            geometry={nodes.개체_1026.geometry}
            material={materials["재질_2.005"]}
            position={[-1.96, -994.37, 110.33]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1027"
            geometry={nodes.개체_1027.geometry}
            material={materials["재질_2.005"]}
            position={[-1.96, -1014.38, 110.33]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1028"
            geometry={nodes.개체_1028.geometry}
            material={materials["재질_2.005"]}
            position={[-1.96, -1029.97, 110.33]}
            rotation={[-Math.PI, 0.74, -Math.PI]}
            scale={3.15}
          />
          <mesh
            name="개체_1029"
            geometry={nodes.개체_1029.geometry}
            material={materials["재질_2.005"]}
            position={[139.22, -1625.66, 55.25]}
            scale={3.15}
          />
          <mesh
            name="개체_1030"
            geometry={nodes.개체_1030.geometry}
            material={materials["재질_2.005"]}
            position={[139.22, -1641.25, 55.25]}
            scale={3.15}
          />
          <mesh
            name="개체_1031"
            geometry={nodes.개체_1031.geometry}
            material={materials["재질_2.005"]}
            position={[139.22, -1656.74, 55.25]}
            scale={3.15}
          />
          <mesh
            name="개체_1032"
            geometry={nodes.개체_1032.geometry}
            material={materials["재질_2.005"]}
            position={[139.22, -1672.33, 55.25]}
            scale={3.15}
          />
          <mesh
            name="개체_1033"
            geometry={nodes.개체_1033.geometry}
            material={materials["재질_2.005"]}
            position={[138.4, -1688.32, 57.7]}
            scale={3.15}
          />
          <mesh
            name="개체_1034"
            geometry={nodes.개체_1034.geometry}
            material={materials["재질_2.005"]}
            position={[138.4, -1703.91, 57.7]}
            scale={3.15}
          />
          <mesh
            name="개체_1035"
            geometry={nodes.개체_1035.geometry}
            material={materials["재질_2.005"]}
            position={[138.4, -1723.92, 57.7]}
            scale={3.15}
          />
          <mesh
            name="개체_1036"
            geometry={nodes.개체_1036.geometry}
            material={materials["재질_2.005"]}
            position={[138.4, -1739.5, 57.7]}
            scale={3.15}
          />
          <mesh
            name="개체_1037"
            geometry={nodes.개체_1037.geometry}
            material={materials["재질_2.005"]}
            position={[-314.41, -1599.23, -7.66]}
            scale={4.64}
          />
          <mesh
            name="개체_1038"
            geometry={nodes.개체_1038.geometry}
            material={materials["재질_2.005"]}
            position={[-314.41, -1622.2, -7.66]}
            scale={4.64}
          />
          <mesh
            name="개체_1039"
            geometry={nodes.개체_1039.geometry}
            material={materials["재질_2.005"]}
            position={[-314.41, -1645.03, -7.66]}
            scale={4.64}
          />
          <mesh
            name="개체_1040"
            geometry={nodes.개체_1040.geometry}
            material={materials["재질_2.005"]}
            position={[-314.41, -1668.01, -7.66]}
            scale={4.64}
          />
          <mesh
            name="개체_1041"
            geometry={nodes.개체_1041.geometry}
            material={materials["재질_2.005"]}
            position={[-315.61, -1691.57, -4.04]}
            scale={4.64}
          />
          <mesh
            name="개체_1042"
            geometry={nodes.개체_1042.geometry}
            material={materials["재질_2.005"]}
            position={[-315.61, -1714.54, -4.04]}
            scale={4.64}
          />
          <mesh
            name="개체_1043"
            geometry={nodes.개체_1043.geometry}
            material={materials["재질_2.005"]}
            position={[-315.61, -1744.03, -4.04]}
            scale={4.64}
          />
          <mesh
            name="개체_1044"
            geometry={nodes.개체_1044.geometry}
            material={materials["재질_2.005"]}
            position={[-315.61, -1767, -4.04]}
            scale={4.64}
          />
          <mesh
            name="개체_1045"
            geometry={nodes.개체_1045.geometry}
            material={materials["재질_2.005"]}
            position={[398.05, -2547.28, -118.39]}
            scale={6.34}
          />
          <mesh
            name="개체_1046"
            geometry={nodes.개체_1046.geometry}
            material={materials["재질_2.005"]}
            position={[398.05, -2578.67, -118.39]}
            scale={6.34}
          />
          <mesh
            name="개체_1053"
            geometry={nodes.개체_1053.geometry}
            material={materials["재질_2.005"]}
            position={[24.47, -2349.44, -201.22]}
            scale={6.34}
          />
          <mesh
            name="개체_1054"
            geometry={nodes.개체_1054.geometry}
            material={materials["재질_2.005"]}
            position={[24.47, -2380.83, -201.22]}
            scale={6.34}
          />
          <mesh
            name="개체_1055"
            geometry={nodes.개체_1055.geometry}
            material={materials["재질_2.005"]}
            position={[24.47, -2412.02, -201.22]}
            scale={6.34}
          />
          <mesh
            name="개체_1056"
            geometry={nodes.개체_1056.geometry}
            material={materials["재질_2.005"]}
            position={[24.47, -2443.41, -201.22]}
            scale={6.34}
          />
          <mesh
            name="개체_1057"
            geometry={nodes.개체_1057.geometry}
            material={materials["재질_2.005"]}
            position={[22.83, -2475.61, -196.27]}
            scale={6.34}
          />
          <mesh
            name="개체_1058"
            geometry={nodes.개체_1058.geometry}
            material={materials["재질_2.005"]}
            position={[22.83, -2506.99, -196.27]}
            scale={6.34}
          />
          <mesh
            name="개체_1059"
            geometry={nodes.개체_1059.geometry}
            material={materials["재질_2.005"]}
            position={[22.83, -2547.28, -196.27]}
            scale={6.34}
          />
          <mesh
            name="개체_1060"
            geometry={nodes.개체_1060.geometry}
            material={materials["재질_2.005"]}
            position={[22.83, -2578.67, -196.27]}
            scale={6.34}
          />
        </group>
        <mesh
          name="Box148001"
          geometry={nodes.Box148001.geometry}
          material={materials.Standardmaterial_3}
          position={[-3870.05, -153.88, 2010.22]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.41}
        />
        <group
          name="G_7001"
          position={[-3870.35, -132.52, 1969.18]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.26}
        >
          <mesh
            name="Mesh481"
            geometry={nodes.Mesh481.geometry}
            material={materials.Standardmaterial_3}
          />
          <mesh
            name="Mesh481_1"
            geometry={nodes.Mesh481_1.geometry}
            material={materials["Material #25"]}
          />
        </group>
        <group
          name="G_8001"
          position={[-3870.35, -132.52, 1993.21]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.26}
        >
          <mesh
            name="Mesh482"
            geometry={nodes.Mesh482.geometry}
            material={materials.Standardmaterial_3}
          />
          <mesh
            name="Mesh482_1"
            geometry={nodes.Mesh482_1.geometry}
            material={materials["Material #25"]}
          />
        </group>
        <mesh
          name="Plane004001"
          geometry={nodes.Plane004001.geometry}
          material={materials.Standardmaterial_3}
          position={[-3870.35, -132.52, 1982.35]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.26}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/dipak.gltf");
