/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Kemra(props) {
  const { nodes, materials } = useGLTF("/kemra.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-4.73, -6.59, -37.41]} rotation={[-0.03, -0.14, 0.55]} scale={0.01}>
        <mesh
          geometry={nodes["3414035_MH"].geometry}
          material={materials["Material1.001"]}
          position={[-1440, -1256.95, -867.32]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes["3414035_MH002"].geometry}
          material={materials["Material1.001"]}
          position={[-1483.06, -1169.98, -2828.32]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes["3414035_MH003"].geometry}
          material={materials["Material1.001"]}
          position={[-1527.33, -1080.57, -4844.54]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes["3414035_MH004"].geometry}
          material={materials["Material1.001"]}
          position={[-1570.39, -993.6, -6805.54]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.Object022.geometry}
          material={materials["Material19.001"]}
          position={[615.74, 362.3, 253.2]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.Object022002.geometry}
          material={materials["Material19.001"]}
          position={[572.68, 449.27, -1707.8]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.Object022003.geometry}
          material={materials["Material19.001"]}
          position={[528.41, 538.68, -3724.02]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.Object022004.geometry}
          material={materials["Material19.001"]}
          position={[485.35, 625.65, -5685.02]}
          rotation={[-1.53, -0.01, 0.02]}
        />
      </group>
      <group position={[-4.87, -6.56, -36.46]} rotation={[-0.03, -0.14, 0.55]} scale={0.01}>
        <group position={[762.33, 253.62, 388.58]}>
          <mesh
            geometry={nodes["8230015_MH001"].geometry}
            material={materials["Material1.001"]}
            position={[-1067.64, -508.27, -612.7]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes["8230015_MH002"].geometry}
            material={materials["Material1.001"]}
            position={[-1208.16, -411.7, -249.95]}
            rotation={[-1.53, -0.01, 0.02]}
          />
          <mesh
            geometry={nodes["8230015_MH003"].geometry}
            material={materials["Material1.001"]}
            position={[-1251.22, -324.74, -2210.94]}
            rotation={[-1.53, -0.01, 0.02]}
          />
          <mesh
            geometry={nodes["8230015_MH004"].geometry}
            material={materials["Material1.001"]}
            position={[-1295.49, -235.32, -4227.16]}
            rotation={[-1.53, -0.01, 0.02]}
          />
          <mesh
            geometry={nodes["8230015_MH005"].geometry}
            material={materials["Material1.001"]}
            position={[-1338.55, -148.36, -6188.16]}
            rotation={[-1.53, -0.01, 0.02]}
          />
        </group>
        <mesh
          geometry={nodes["3401021_MH001"].geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["3401022_MH001"].geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh004.geometry} material={materials["Converted_铝合金.001"]} />
          <mesh geometry={nodes.Mesh004_1.geometry} material={materials["Material3.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh005.geometry} material={materials["Material22.001"]} />
          <mesh geometry={nodes.Mesh005_1.geometry} material={materials["Material27.001"]} />
          <mesh geometry={nodes.Mesh005_2.geometry} material={materials["Material2.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh006.geometry} material={materials["Material16.001"]} />
          <mesh geometry={nodes.Mesh006_1.geometry} material={materials["Material17.001"]} />
          <mesh geometry={nodes.Mesh006_2.geometry} material={materials["Material1.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh007.geometry} material={materials["Material4.001"]} />
          <mesh geometry={nodes.Mesh007_1.geometry} material={materials["Material5.001"]} />
          <mesh geometry={nodes.Mesh007_2.geometry} material={materials["Material6.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh008.geometry} material={materials["Material4.001"]} />
          <mesh geometry={nodes.Mesh008_1.geometry} material={materials["Material5.001"]} />
          <mesh geometry={nodes.Mesh008_2.geometry} material={materials["Material6.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh009.geometry} material={materials["Material10.001"]} />
          <mesh geometry={nodes.Mesh009_1.geometry} material={materials["Material26.001"]} />
          <mesh geometry={nodes.Mesh009_2.geometry} material={materials["Material29.001"]} />
          <mesh geometry={nodes.Mesh009_3.geometry} material={materials["Material32.001"]} />
          <mesh geometry={nodes.Mesh009_4.geometry} material={materials["Material33.001"]} />
          <mesh geometry={nodes.Mesh009_5.geometry} material={materials["Material1.001"]} />
        </group>
        <mesh
          geometry={nodes["3407011_MH001"].geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh011.geometry} material={materials["Material40.001"]} />
          <mesh geometry={nodes.Mesh011_1.geometry} material={materials["Material41.001"]} />
          <mesh geometry={nodes.Mesh011_2.geometry} material={materials["Material42.001"]} />
          <mesh geometry={nodes.Mesh011_3.geometry} material={materials["Material1.001"]} />
        </group>
        <group position={[-1398.11, -1341.56, 944.32]} rotation={[-1.53, -0.01, 0.02]}>
          <mesh geometry={nodes.Mesh012.geometry} material={materials["Converted_铝合金.001"]} />
          <mesh geometry={nodes.Mesh012_1.geometry} material={materials["Material3.001"]} />
        </group>
        <mesh
          geometry={nodes["3414035_MH001"].geometry}
          material={materials["Material1.001"]}
          position={[-1398.11, -1341.56, 944.32]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.B25D_32422_A001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.C131_COLM_ASSY_REV5_12_02_08001.geometry}
          material={materials["Material18.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.CQ2180820001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.CQ39714001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FA01_26169001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1398.11, -1341.56, 944.32]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.FQ6101815B001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ6102412B001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99562_1400001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99786_0612001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99796_0620001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99937_0600_5001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99940_0601_4001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99940_0803001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ9YA02_0629001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ9YB04_1208_16001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1398.11, -1341.56, 944.32]}
          rotation={[-1.53, -0.01, 0.02]}
        />
        <mesh
          geometry={nodes.FQB455_32099B001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQH266_28091001.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Object022001.geometry}
          material={materials["Material19.001"]}
          position={[642.21, 308.84, 1362.29]}
          rotation={[-1.53, -0.01, 0.02]}
        />
      </group>
      <group position={[-6.42, -6.44, -39.2]} rotation={[0, -0.1, 0.57]} scale={0.01}>
        <mesh
          geometry={nodes["3401021_MH002"].geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["3401022_MH002"].geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh078.geometry} material={materials["Converted_铝合金.001"]} />
          <mesh geometry={nodes.Mesh078_1.geometry} material={materials["Material3.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh079.geometry} material={materials["Material22.001"]} />
          <mesh geometry={nodes.Mesh079_1.geometry} material={materials["Material27.001"]} />
          <mesh geometry={nodes.Mesh079_2.geometry} material={materials["Material2.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh080.geometry} material={materials["Material16.001"]} />
          <mesh geometry={nodes.Mesh080_1.geometry} material={materials["Material17.001"]} />
          <mesh geometry={nodes.Mesh080_2.geometry} material={materials["Material1.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh081.geometry} material={materials["Material4.001"]} />
          <mesh geometry={nodes.Mesh081_1.geometry} material={materials["Material5.001"]} />
          <mesh geometry={nodes.Mesh081_2.geometry} material={materials["Material6.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh082.geometry} material={materials["Material4.001"]} />
          <mesh geometry={nodes.Mesh082_1.geometry} material={materials["Material5.001"]} />
          <mesh geometry={nodes.Mesh082_2.geometry} material={materials["Material6.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh083.geometry} material={materials["Material10.001"]} />
          <mesh geometry={nodes.Mesh083_1.geometry} material={materials["Material26.001"]} />
          <mesh geometry={nodes.Mesh083_2.geometry} material={materials["Material29.001"]} />
          <mesh geometry={nodes.Mesh083_3.geometry} material={materials["Material32.001"]} />
          <mesh geometry={nodes.Mesh083_4.geometry} material={materials["Material33.001"]} />
          <mesh geometry={nodes.Mesh083_5.geometry} material={materials["Material1.001"]} />
        </group>
        <mesh
          geometry={nodes["3407011_MH002"].geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh085.geometry} material={materials["Material40.001"]} />
          <mesh geometry={nodes.Mesh085_1.geometry} material={materials["Material41.001"]} />
          <mesh geometry={nodes.Mesh085_2.geometry} material={materials["Material42.001"]} />
          <mesh geometry={nodes.Mesh085_3.geometry} material={materials["Material1.001"]} />
        </group>
        <group position={[-1292.78, -1386.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh086.geometry} material={materials["Converted_铝合金.001"]} />
          <mesh geometry={nodes.Mesh086_1.geometry} material={materials["Material3.001"]} />
        </group>
        <mesh
          geometry={nodes.B25D_32422_A002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.C131_COLM_ASSY_REV5_12_02_08002.geometry}
          material={materials["Material18.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.CQ2180820002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.CQ39714002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FA01_26169002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ6101815B002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ6102412B002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99562_1400002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99786_0612002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99796_0620002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99937_0600_5002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99940_0601_4002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ99940_0803002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ9YA02_0629002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQ9YB04_1208_16002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FQB455_32099B002.geometry}
          material={materials["Converted_21 - Def0.001"]}
          position={[-1292.78, -1386.99, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes["uploads_files_882425_SNEAK+HEAD+OBJ001"].geometry}
        material={materials["Material.001"]}
        position={[-14.25, -0.49, -29.82]}
        rotation={[1.58, -0.08, 0.1]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.working_gloves_sub003.geometry}
        material={materials.workin_gloves_shd}
        position={[3.21, -4.6, -29.2]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub004.geometry}
        material={materials.workin_gloves_shd}
        position={[3.79, -3.92, -32.76]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub005.geometry}
        material={materials.workin_gloves_shd}
        position={[3.21, -4.6, -29.2]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub006.geometry}
        material={materials.workin_gloves_shd}
        position={[2.43, -4.59, -21.42]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub007.geometry}
        material={materials.workin_gloves_shd}
        position={[3.01, -3.92, -24.98]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub008.geometry}
        material={materials.workin_gloves_shd}
        position={[2.43, -4.59, -21.42]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub009.geometry}
        material={materials.workin_gloves_shd}
        position={[3.01, -3.92, -24.98]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub010.geometry}
        material={materials.workin_gloves_shd}
        position={[3.79, -3.92, -32.76]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub011.geometry}
        material={materials.workin_gloves_shd}
        position={[3.97, -4.6, -36.73]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub012.geometry}
        material={materials.workin_gloves_shd}
        position={[4.55, -3.92, -40.29]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub013.geometry}
        material={materials.workin_gloves_shd}
        position={[3.97, -4.6, -36.73]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub014.geometry}
        material={materials.workin_gloves_shd}
        position={[4.55, -3.92, -40.29]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub015.geometry}
        material={materials.workin_gloves_shd}
        position={[4.76, -4.6, -44.51]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub016.geometry}
        material={materials.workin_gloves_shd}
        position={[5.34, -3.92, -48.07]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub017.geometry}
        material={materials.workin_gloves_shd}
        position={[4.76, -4.6, -44.51]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub018.geometry}
        material={materials.workin_gloves_shd}
        position={[5.34, -3.92, -48.07]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub019.geometry}
        material={materials.workin_gloves_shd}
        position={[5.7, -4.2, -52.53]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub020.geometry}
        material={materials.workin_gloves_shd}
        position={[6.28, -3.52, -56.09]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub021.geometry}
        material={materials.workin_gloves_shd}
        position={[5.7, -4.2, -52.53]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub022.geometry}
        material={materials.workin_gloves_shd}
        position={[6.28, -3.52, -56.09]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub023.geometry}
        material={materials.workin_gloves_shd}
        position={[6.49, -4.2, -60.31]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub024.geometry}
        material={materials.workin_gloves_shd}
        position={[7.07, -3.52, -63.87]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub025.geometry}
        material={materials.workin_gloves_shd}
        position={[6.49, -4.2, -60.31]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub026.geometry}
        material={materials.workin_gloves_shd}
        position={[7.07, -3.52, -63.87]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub027.geometry}
        material={materials.workin_gloves_shd}
        position={[7.24, -4.2, -67.84]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub028.geometry}
        material={materials.workin_gloves_shd}
        position={[7.82, -3.52, -71.4]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub029.geometry}
        material={materials.workin_gloves_shd}
        position={[7.24, -4.2, -67.84]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub030.geometry}
        material={materials.workin_gloves_shd}
        position={[7.82, -3.52, -71.4]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub031.geometry}
        material={materials.workin_gloves_shd}
        position={[8.03, -4.2, -75.62]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub032.geometry}
        material={materials.workin_gloves_shd}
        position={[8.61, -3.52, -79.18]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub033.geometry}
        material={materials.workin_gloves_shd}
        position={[8.03, -4.2, -75.62]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.working_gloves_sub034.geometry}
        material={materials.workin_gloves_shd}
        position={[8.61, -3.52, -79.18]}
        rotation={[1.57, 0.56, 2.04]}
        scale={0.12}
      />
      <mesh
        geometry={nodes["uploads_files_882425_SNEAK+HEAD+OBJ002"].geometry}
        material={materials["Material.001"]}
        position={[15.16, -1.37, -53.22]}
        rotation={[1.58, -0.08, 0.1]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/kemra.gltf");
