/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Sunyena(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/sunyena.gltf");
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="cool_gray"
          position={[1.55, -0.95, -32.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1016"
            geometry={nodes.Object_1016.geometry}
            material={materials.Material_2}
            position={[0, 259.39, 0]}
          />
        </group>
        <group
          name="cool_gray002"
          position={[1.57, -1.03, -44.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1071"
            geometry={nodes.Object_1071.geometry}
            material={materials["Material_2.001"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1073"
            geometry={nodes.Object_1073.geometry}
            material={materials["Material_2.001"]}
            position={[65.21, 161.99, 0]}
          />
        </group>
        <group
          name="cool_gray003"
          position={[1.55, -0.95, -32.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1101"
            geometry={nodes.Object_1101.geometry}
            material={materials["Material_2.001"]}
            position={[0, 99.81, 0]}
          />
        </group>
        <group
          name="레이어_01"
          position={[-5.28, 2.36, -41.46]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh name="개체_24" geometry={nodes.개체_24.geometry} material={materials.재질_2} />
          <mesh name="개체_25" geometry={nodes.개체_25.geometry} material={materials.재질_2} />
          <mesh name="개체_26" geometry={nodes.개체_26.geometry} material={materials.재질_2} />
          <mesh name="개체_27" geometry={nodes.개체_27.geometry} material={materials.재질_2} />
          <mesh name="개체_28" geometry={nodes.개체_28.geometry} material={materials.재질_2} />
          <mesh name="개체_29" geometry={nodes.개체_29.geometry} material={materials.재질_2} />
          <mesh name="개체_3" geometry={nodes.개체_3.geometry} material={materials.재질_2} />
          <mesh name="개체_30" geometry={nodes.개체_30.geometry} material={materials.재질_2} />
          <mesh name="개체_31" geometry={nodes.개체_31.geometry} material={materials.재질_2} />
          <mesh name="개체_32" geometry={nodes.개체_32.geometry} material={materials.재질_2} />
          <mesh name="개체_33" geometry={nodes.개체_33.geometry} material={materials.재질_2} />
          <mesh name="개체_34" geometry={nodes.개체_34.geometry} material={materials.재질_2} />
          <mesh name="개체_35" geometry={nodes.개체_35.geometry} material={materials.재질_2} />
          <mesh name="개체_36" geometry={nodes.개체_36.geometry} material={materials.재질_2} />
          <mesh name="개체_37" geometry={nodes.개체_37.geometry} material={materials.재질_2} />
          <mesh name="개체_38" geometry={nodes.개체_38.geometry} material={materials.재질_2} />
          <mesh name="개체_39" geometry={nodes.개체_39.geometry} material={materials.재질_2} />
          <mesh name="개체_40" geometry={nodes.개체_40.geometry} material={materials.재질_2} />
          <mesh name="개체_41" geometry={nodes.개체_41.geometry} material={materials.재질_2} />
          <mesh name="개체_42" geometry={nodes.개체_42.geometry} material={materials.재질_2} />
          <mesh name="개체_43" geometry={nodes.개체_43.geometry} material={materials.재질_2} />
          <mesh name="개체_44" geometry={nodes.개체_44.geometry} material={materials.재질_2} />
          <mesh name="개체_45" geometry={nodes.개체_45.geometry} material={materials.재질_2} />
          <mesh name="개체_46" geometry={nodes.개체_46.geometry} material={materials.재질_2} />
          <mesh name="개체_47" geometry={nodes.개체_47.geometry} material={materials.재질_2} />
          <mesh name="개체_48" geometry={nodes.개체_48.geometry} material={materials.재질_2} />
          <mesh name="개체_49" geometry={nodes.개체_49.geometry} material={materials.재질_2} />
          <mesh name="개체_6" geometry={nodes.개체_6.geometry} material={materials.재질_2} />
          <mesh name="개체_7" geometry={nodes.개체_7.geometry} material={materials.재질_2} />
        </group>
        <group
          name="레이어_01001"
          position={[-5.49, 1.43, -44.47]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_3001"
            geometry={nodes.개체_3001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_31001"
            geometry={nodes.개체_31001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_32001"
            geometry={nodes.개체_32001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_33001"
            geometry={nodes.개체_33001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_34001"
            geometry={nodes.개체_34001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_47001"
            geometry={nodes.개체_47001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_48001"
            geometry={nodes.개체_48001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_49001"
            geometry={nodes.개체_49001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group
          name="레이어_02"
          position={[-5.28, 2.36, -41.46]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh name="개체_1" geometry={nodes.개체_1.geometry} material={materials.재질_2} />
          <mesh name="개체_10" geometry={nodes.개체_10.geometry} material={materials.재질_2} />
          <mesh name="개체_11" geometry={nodes.개체_11.geometry} material={materials.재질_2} />
          <mesh name="개체_12" geometry={nodes.개체_12.geometry} material={materials.재질_2} />
          <mesh name="개체_13" geometry={nodes.개체_13.geometry} material={materials.재질_2} />
          <mesh name="개체_14" geometry={nodes.개체_14.geometry} material={materials.재질_2} />
          <mesh name="개체_15" geometry={nodes.개체_15.geometry} material={materials.재질_2} />
          <mesh name="개체_16" geometry={nodes.개체_16.geometry} material={materials.재질_2} />
          <mesh name="개체_17" geometry={nodes.개체_17.geometry} material={materials.재질_2} />
          <mesh name="개체_18" geometry={nodes.개체_18.geometry} material={materials.재질_2} />
          <mesh name="개체_19" geometry={nodes.개체_19.geometry} material={materials.재질_2} />
          <mesh name="개체_20" geometry={nodes.개체_20.geometry} material={materials.재질_2} />
          <mesh name="개체_21" geometry={nodes.개체_21.geometry} material={materials.재질_2} />
          <mesh name="개체_22" geometry={nodes.개체_22.geometry} material={materials.재질_2} />
          <mesh name="개체_23" geometry={nodes.개체_23.geometry} material={materials.재질_2} />
          <mesh name="개체_4" geometry={nodes.개체_4.geometry} material={materials.재질_2} />
          <mesh name="개체_5" geometry={nodes.개체_5.geometry} material={materials.재질_2} />
          <mesh name="개체_50" geometry={nodes.개체_50.geometry} material={materials.재질_2} />
          <mesh name="개체_8" geometry={nodes.개체_8.geometry} material={materials.재질_2} />
          <mesh name="개체_9" geometry={nodes.개체_9.geometry} material={materials.재질_2} />
        </group>
        <group
          name="레이어_02001"
          position={[-5.49, 1.43, -44.47]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_13001"
            geometry={nodes.개체_13001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_14001"
            geometry={nodes.개체_14001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_15001"
            geometry={nodes.개체_15001.geometry}
            material={materials.재질_2}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group
          name="cool_gray011"
          position={[1.55, -0.95, -32.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1413"
            geometry={nodes.Object_1413.geometry}
            material={materials["Material_2.003"]}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1418"
            geometry={nodes.Object_1418.geometry}
            material={materials["Material_2.003"]}
            position={[0, 177.24, 0]}
          />
          <mesh
            name="Object_1423"
            geometry={nodes.Object_1423.geometry}
            material={materials["Material_2.003"]}
            position={[0, 259.39, 0]}
          />
        </group>
        <group
          name="cool_gray010"
          position={[1.57, -1.03, -44.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1383"
            geometry={nodes.Object_1383.geometry}
            material={materials["Material_2.003"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1407"
            geometry={nodes.Object_1407.geometry}
            material={materials["Material_2.003"]}
          />
        </group>
        <group
          name="cool_gray009"
          position={[1.57, -1.03, -44.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1344"
            geometry={nodes.Object_1344.geometry}
            material={materials["Material_2.002"]}
          />
          <mesh
            name="Object_1362"
            geometry={nodes.Object_1362.geometry}
            material={materials["Material_2.002"]}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1366"
            geometry={nodes.Object_1366.geometry}
            material={materials["Material_2.002"]}
            position={[65.21, 161.99, 0]}
          />
          <mesh
            name="Object_1368"
            geometry={nodes.Object_1368.geometry}
            material={materials["Material_2.002"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1372"
            geometry={nodes.Object_1372.geometry}
            material={materials["Material_2.002"]}
            position={[0, 66.93, 0]}
          />
        </group>
        <group
          name="cool_gray008"
          position={[1.55, -0.95, -32.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1338"
            geometry={nodes.Object_1338.geometry}
            material={materials["Material_2.002"]}
            position={[0, 99.81, 0]}
          />
        </group>
        <group
          name="cool_gray006"
          position={[2.16, -1.32, -85.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.03}
        >
          <mesh
            name="Object_1282"
            geometry={nodes.Object_1282.geometry}
            material={materials["Material_2.002"]}
            position={[0, -241.73, 0]}
          />
        </group>
        <group
          name="레이어_01003"
          position={[-5.28, 2.36, -41.46]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh
            name="개체_24003"
            geometry={nodes.개체_24003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_25003"
            geometry={nodes.개체_25003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_26003"
            geometry={nodes.개체_26003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_27003"
            geometry={nodes.개체_27003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_28003"
            geometry={nodes.개체_28003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_29003"
            geometry={nodes.개체_29003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_3003"
            geometry={nodes.개체_3003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_30003"
            geometry={nodes.개체_30003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_31003"
            geometry={nodes.개체_31003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_32003"
            geometry={nodes.개체_32003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_33003"
            geometry={nodes.개체_33003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_34003"
            geometry={nodes.개체_34003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_35003"
            geometry={nodes.개체_35003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_36003"
            geometry={nodes.개체_36003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_37003"
            geometry={nodes.개체_37003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_38003"
            geometry={nodes.개체_38003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_39003"
            geometry={nodes.개체_39003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_40003"
            geometry={nodes.개체_40003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_41003"
            geometry={nodes.개체_41003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_42003"
            geometry={nodes.개체_42003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_43003"
            geometry={nodes.개체_43003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_44003"
            geometry={nodes.개체_44003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_45003"
            geometry={nodes.개체_45003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_46003"
            geometry={nodes.개체_46003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_47003"
            geometry={nodes.개체_47003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_48003"
            geometry={nodes.개체_48003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_49003"
            geometry={nodes.개체_49003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_6003"
            geometry={nodes.개체_6003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_7003"
            geometry={nodes.개체_7003.geometry}
            material={materials["재질_2.001"]}
          />
        </group>
        <group
          name="레이어_01002"
          position={[-5.49, 1.43, -44.47]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_3002"
            geometry={nodes.개체_3002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_31002"
            geometry={nodes.개체_31002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_32002"
            geometry={nodes.개체_32002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_33002"
            geometry={nodes.개체_33002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_34002"
            geometry={nodes.개체_34002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_47002"
            geometry={nodes.개체_47002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_48002"
            geometry={nodes.개체_48002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_49002"
            geometry={nodes.개체_49002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group
          name="레이어_02003"
          position={[-5.28, 2.36, -41.46]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh
            name="개체_1003"
            geometry={nodes.개체_1003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_10003"
            geometry={nodes.개체_10003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_11003"
            geometry={nodes.개체_11003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_12003"
            geometry={nodes.개체_12003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_13003"
            geometry={nodes.개체_13003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_14003"
            geometry={nodes.개체_14003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_15003"
            geometry={nodes.개체_15003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_16003"
            geometry={nodes.개체_16003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_17003"
            geometry={nodes.개체_17003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_18003"
            geometry={nodes.개체_18003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_19003"
            geometry={nodes.개체_19003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_20003"
            geometry={nodes.개체_20003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_21003"
            geometry={nodes.개체_21003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_22003"
            geometry={nodes.개체_22003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_23003"
            geometry={nodes.개체_23003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_4003"
            geometry={nodes.개체_4003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_5003"
            geometry={nodes.개체_5003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_50003"
            geometry={nodes.개체_50003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_8003"
            geometry={nodes.개체_8003.geometry}
            material={materials["재질_2.001"]}
          />
          <mesh
            name="개체_9003"
            geometry={nodes.개체_9003.geometry}
            material={materials["재질_2.001"]}
          />
        </group>
        <group
          name="레이어_02002"
          position={[-5.49, 1.43, -44.47]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_13002"
            geometry={nodes.개체_13002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_14002"
            geometry={nodes.개체_14002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_15002"
            geometry={nodes.개체_15002.geometry}
            material={materials["재질_2.001"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group
          name="cool_gray017"
          position={[1.55, -0.95, -32.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1633"
            geometry={nodes.Object_1633.geometry}
            material={materials["Material_2.005"]}
            position={[0, 99.81, 0]}
          />
          <mesh
            name="Object_1636"
            geometry={nodes.Object_1636.geometry}
            material={materials["Material_2.005"]}
            position={[0, 145.89, 0]}
          />
          <mesh
            name="Object_1640"
            geometry={nodes.Object_1640.geometry}
            material={materials["Material_2.005"]}
            position={[0, 210.13, 0]}
          />
        </group>
        <group
          name="cool_gray016"
          position={[1.57, -1.03, -44.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1603"
            geometry={nodes.Object_1603.geometry}
            material={materials["Material_2.005"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1609"
            geometry={nodes.Object_1609.geometry}
            material={materials["Material_2.005"]}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1627"
            geometry={nodes.Object_1627.geometry}
            material={materials["Material_2.005"]}
          />
        </group>
        <group
          name="cool_gray015"
          position={[1.57, -1.03, -44.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1564"
            geometry={nodes.Object_1564.geometry}
            material={materials["Material_2.004"]}
          />
          <mesh
            name="Object_1571"
            geometry={nodes.Object_1571.geometry}
            material={materials["Material_2.004"]}
            position={[0, -113.5, 0]}
          />
          <mesh
            name="Object_1582"
            geometry={nodes.Object_1582.geometry}
            material={materials["Material_2.004"]}
            position={[0, 228.04, 0]}
          />
          <mesh
            name="Object_1586"
            geometry={nodes.Object_1586.geometry}
            material={materials["Material_2.004"]}
            position={[65.21, 161.99, 0]}
          />
          <mesh
            name="Object_1588"
            geometry={nodes.Object_1588.geometry}
            material={materials["Material_2.004"]}
            position={[0, 131.16, 0]}
          />
          <mesh
            name="Object_1592"
            geometry={nodes.Object_1592.geometry}
            material={materials["Material_2.004"]}
            position={[0, 66.93, 0]}
          />
        </group>
        <group
          name="cool_gray014"
          position={[1.55, -0.95, -32.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        >
          <mesh
            name="Object_1541"
            geometry={nodes.Object_1541.geometry}
            material={materials["Material_2.004"]}
          />
          <mesh
            name="Object_1545"
            geometry={nodes.Object_1545.geometry}
            material={materials["Material_2.004"]}
            position={[0, -64.23, 0]}
          />
          <mesh
            name="Object_1554"
            geometry={nodes.Object_1554.geometry}
            material={materials["Material_2.004"]}
            position={[0, -210.38, 0]}
          />
          <mesh
            name="Object_1561"
            geometry={nodes.Object_1561.geometry}
            material={materials["Material_2.004"]}
            position={[0, 49.01, 0]}
          />
        </group>
        <group
          name="cool_gray013"
          position={[2.06, -1.41, -68.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.03}
        >
          <mesh
            name="Object_1522"
            geometry={nodes.Object_1522.geometry}
            material={materials["Material_2.004"]}
            position={[0, 81.9, 0]}
          />
          <mesh
            name="Object_1523"
            geometry={nodes.Object_1523.geometry}
            material={materials["Material_2.004"]}
            position={[-3.96, 89.51, -153.3]}
          />
          <mesh
            name="Object_1524"
            geometry={nodes.Object_1524.geometry}
            material={materials["Material_2.004"]}
            position={[-125.62, 82.95, 22.97]}
          />
          <mesh
            name="Object_1527"
            geometry={nodes.Object_1527.geometry}
            material={materials["Material_2.004"]}
            position={[-133.74, -188.51, -52.33]}
          />
          <mesh
            name="Object_1528"
            geometry={nodes.Object_1528.geometry}
            material={materials["Material_2.004"]}
            position={[0, -192.46, 0]}
          />
          <mesh
            name="Object_1535"
            geometry={nodes.Object_1535.geometry}
            material={materials["Material_2.004"]}
            position={[0, -82.15, 0]}
          />
          <mesh
            name="Object_1540"
            geometry={nodes.Object_1540.geometry}
            material={materials["Material_2.004"]}
          />
        </group>
        <group
          name="cool_gray012"
          position={[2.16, -1.32, -85.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.03}
        >
          <mesh
            name="Object_1488"
            geometry={nodes.Object_1488.geometry}
            material={materials["Material_2.004"]}
            position={[0, 49.01, 0]}
          />
          <mesh
            name="Object_1495"
            geometry={nodes.Object_1495.geometry}
            material={materials["Material_2.004"]}
            position={[0, 163.81, 0]}
          />
          <mesh
            name="Object_1502"
            geometry={nodes.Object_1502.geometry}
            material={materials["Material_2.004"]}
            position={[0, -241.73, 0]}
          />
          <mesh
            name="Object_1507"
            geometry={nodes.Object_1507.geometry}
            material={materials["Material_2.004"]}
            position={[0, -159.58, 0]}
          />
        </group>
        <group
          name="레이어_01005"
          position={[-5.28, 2.36, -41.46]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh
            name="개체_24005"
            geometry={nodes.개체_24005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_25005"
            geometry={nodes.개체_25005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_26005"
            geometry={nodes.개체_26005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_27005"
            geometry={nodes.개체_27005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_28005"
            geometry={nodes.개체_28005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_29005"
            geometry={nodes.개체_29005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_3005"
            geometry={nodes.개체_3005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_30005"
            geometry={nodes.개체_30005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_31005"
            geometry={nodes.개체_31005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_32005"
            geometry={nodes.개체_32005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_33005"
            geometry={nodes.개체_33005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_34005"
            geometry={nodes.개체_34005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_35005"
            geometry={nodes.개체_35005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_36005"
            geometry={nodes.개체_36005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_37005"
            geometry={nodes.개체_37005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_38005"
            geometry={nodes.개체_38005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_39005"
            geometry={nodes.개체_39005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_40005"
            geometry={nodes.개체_40005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_41005"
            geometry={nodes.개체_41005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_42005"
            geometry={nodes.개체_42005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_43005"
            geometry={nodes.개체_43005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_44005"
            geometry={nodes.개체_44005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_45005"
            geometry={nodes.개체_45005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_46005"
            geometry={nodes.개체_46005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_47005"
            geometry={nodes.개체_47005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_48005"
            geometry={nodes.개체_48005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_49005"
            geometry={nodes.개체_49005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_6005"
            geometry={nodes.개체_6005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_7005"
            geometry={nodes.개체_7005.geometry}
            material={materials["재질_2.002"]}
          />
        </group>
        <group
          name="레이어_01004"
          position={[-5.49, 1.43, -44.47]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_3004"
            geometry={nodes.개체_3004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_31004"
            geometry={nodes.개체_31004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_32004"
            geometry={nodes.개체_32004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_33004"
            geometry={nodes.개체_33004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_34004"
            geometry={nodes.개체_34004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_47004"
            geometry={nodes.개체_47004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_48004"
            geometry={nodes.개체_48004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_49004"
            geometry={nodes.개체_49004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group
          name="레이어_02005"
          position={[-5.28, 2.36, -41.46]}
          rotation={[0.12, -0.21, 0.13]}
          scale={0}
        >
          <mesh
            name="개체_1005"
            geometry={nodes.개체_1005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_10005"
            geometry={nodes.개체_10005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_11005"
            geometry={nodes.개체_11005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_12005"
            geometry={nodes.개체_12005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_13005"
            geometry={nodes.개체_13005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_14005"
            geometry={nodes.개체_14005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_15005"
            geometry={nodes.개체_15005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_16005"
            geometry={nodes.개체_16005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_17005"
            geometry={nodes.개체_17005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_18005"
            geometry={nodes.개체_18005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_19005"
            geometry={nodes.개체_19005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_20005"
            geometry={nodes.개체_20005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_21005"
            geometry={nodes.개체_21005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_22005"
            geometry={nodes.개체_22005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_23005"
            geometry={nodes.개체_23005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_4005"
            geometry={nodes.개체_4005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_5005"
            geometry={nodes.개체_5005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_50005"
            geometry={nodes.개체_50005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_8005"
            geometry={nodes.개체_8005.geometry}
            material={materials["재질_2.002"]}
          />
          <mesh
            name="개체_9005"
            geometry={nodes.개체_9005.geometry}
            material={materials["재질_2.002"]}
          />
        </group>
        <group
          name="레이어_02004"
          position={[-5.49, 1.43, -44.47]}
          rotation={[2.15, -1.43, 2.25]}
          scale={0}
        >
          <mesh
            name="개체_13004"
            geometry={nodes.개체_13004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_14004"
            geometry={nodes.개체_14004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
          <mesh
            name="개체_15004"
            geometry={nodes.개체_15004.geometry}
            material={materials["재질_2.002"]}
            position={[-5060.93, -1451.97, -2676.8]}
            rotation={[0.46, 1.17, -0.47]}
          />
        </group>
        <group name="Camera004" position={[0, 0, -0.16]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh
          name="Plant_02"
          geometry={nodes.Plant_02.geometry}
          material={materials.Plant_02}
          position={[1.78, -2.02, -22.07]}
          scale={0.06}
        />
        <mesh
          name="Plant_03001"
          geometry={nodes.Plant_03001.geometry}
          material={materials.Plant_03}
          position={[3.91, -2.32, -60.38]}
          scale={0.2}
        />
        <mesh
          name="Plant_04"
          geometry={nodes.Plant_04.geometry}
          material={materials.Plant_04}
          position={[-4.71, -7.63, -94.68]}
          scale={0.42}
        />
        <group name="Pot" position={[2.74, 0.23, -74.62]} rotation={[0, 0.28, 0]} scale={12.95}>
          <mesh
            name="Circle001"
            geometry={nodes.Circle001.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Circle001_1"
            geometry={nodes.Circle001_1.geometry}
            material={materials.Ground}
          />
          <mesh
            name="Circle001_2"
            geometry={nodes.Circle001_2.geometry}
            material={materials.GreenStones}
          />
        </group>
        <mesh
          name="Sucu_longL_02"
          geometry={nodes.Sucu_longL_02.geometry}
          material={materials.stem}
          position={[2.98, 0.28, -74.59]}
          rotation={[1.51, -0.06, 0.01]}
          scale={[12.95, 12.95, 12.37]}
        />
        <mesh
          name="Sucu_longM_01"
          geometry={nodes.Sucu_longM_01.geometry}
          material={materials.stem}
          position={[2.82, 0.25, -74.4]}
          rotation={[1.59, 0.11, 2.74]}
          scale={10.65}
        />
        <mesh
          name="Sucu_ShortL_02"
          geometry={nodes.Sucu_ShortL_02.geometry}
          material={materials.stem}
          position={[2.56, 0.26, -74.69]}
          rotation={[1.54, 0.14, -2.18]}
          scale={[10.62, 10.62, 9.67]}
        />
        <mesh
          name="Sucu_ShortS_01"
          geometry={nodes.Sucu_ShortS_01.geometry}
          material={materials.Plant_04}
          position={[2.87, 0.26, -74.86]}
          rotation={[1.48, -0.05, -0.28]}
          scale={[7.36, 7.36, 6.84]}
        />
        <mesh
          name="Plant_02001"
          geometry={nodes.Plant_02001.geometry}
          material={materials["Plant_02.001"]}
          position={[1.78, -2.02, -22.07]}
          scale={0.06}
        />
        <mesh
          name="Plant_03002"
          geometry={nodes.Plant_03002.geometry}
          material={materials["Plant_03.001"]}
          position={[3.91, -2.32, -60.38]}
          scale={0.2}
        />
        <mesh
          name="Plant_04001"
          geometry={nodes.Plant_04001.geometry}
          material={materials["Plant_04.001"]}
          position={[-4.71, -7.63, -94.68]}
          scale={0.42}
        />
        <group name="Pot001" position={[2.74, 0.23, -74.62]} rotation={[0, 0.28, 0]} scale={12.95}>
          <mesh
            name="Circle002"
            geometry={nodes.Circle002.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Circle002_1"
            geometry={nodes.Circle002_1.geometry}
            material={materials["Ground.001"]}
          />
          <mesh
            name="Circle002_2"
            geometry={nodes.Circle002_2.geometry}
            material={materials["GreenStones.001"]}
          />
        </group>
        <mesh
          name="Sucu_longL_02001"
          geometry={nodes.Sucu_longL_02001.geometry}
          material={materials["stem.001"]}
          position={[2.98, 0.28, -74.59]}
          rotation={[1.51, -0.06, 0.01]}
          scale={[12.95, 12.95, 12.37]}
        />
        <mesh
          name="Sucu_longM_01001"
          geometry={nodes.Sucu_longM_01001.geometry}
          material={materials["stem.001"]}
          position={[2.82, 0.25, -74.4]}
          rotation={[1.59, 0.11, 2.74]}
          scale={10.65}
        />
        <mesh
          name="Sucu_ShortL_02001"
          geometry={nodes.Sucu_ShortL_02001.geometry}
          material={materials["stem.001"]}
          position={[2.56, 0.26, -74.69]}
          rotation={[1.54, 0.14, -2.18]}
          scale={[10.62, 10.62, 9.67]}
        />
        <mesh
          name="Sucu_ShortS_01001"
          geometry={nodes.Sucu_ShortS_01001.geometry}
          material={materials["Plant_04.001"]}
          position={[2.87, 0.26, -74.86]}
          rotation={[1.48, -0.05, -0.28]}
          scale={[7.36, 7.36, 6.84]}
        />
        <mesh
          name="Plant_02002"
          geometry={nodes.Plant_02002.geometry}
          material={materials["Plant_02.002"]}
          position={[1.78, -2.02, -22.07]}
          scale={0.06}
        />
        <mesh
          name="Plant_03004"
          geometry={nodes.Plant_03004.geometry}
          material={materials["Plant_03.002"]}
          position={[3.91, -2.32, -60.38]}
          scale={0.2}
        />
        <mesh
          name="Plant_04002"
          geometry={nodes.Plant_04002.geometry}
          material={materials["Plant_04.002"]}
          position={[-4.71, -7.63, -94.68]}
          scale={0.42}
        />
        <group name="Pot002" position={[2.74, 0.23, -74.62]} rotation={[0, 0.28, 0]} scale={12.95}>
          <mesh
            name="Circle003"
            geometry={nodes.Circle003.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Circle003_1"
            geometry={nodes.Circle003_1.geometry}
            material={materials["Ground.002"]}
          />
          <mesh
            name="Circle003_2"
            geometry={nodes.Circle003_2.geometry}
            material={materials["GreenStones.002"]}
          />
        </group>
        <mesh
          name="Sucu_longL_02002"
          geometry={nodes.Sucu_longL_02002.geometry}
          material={materials["stem.002"]}
          position={[2.98, 0.28, -74.59]}
          rotation={[1.51, -0.06, 0.01]}
          scale={[12.95, 12.95, 12.37]}
        />
        <mesh
          name="Sucu_longM_01002"
          geometry={nodes.Sucu_longM_01002.geometry}
          material={materials["stem.002"]}
          position={[2.82, 0.25, -74.4]}
          rotation={[1.59, 0.11, 2.74]}
          scale={10.65}
        />
        <mesh
          name="Sucu_ShortL_02002"
          geometry={nodes.Sucu_ShortL_02002.geometry}
          material={materials["stem.002"]}
          position={[2.56, 0.26, -74.69]}
          rotation={[1.54, 0.14, -2.18]}
          scale={[10.62, 10.62, 9.67]}
        />
        <mesh
          name="Sucu_ShortS_01002"
          geometry={nodes.Sucu_ShortS_01002.geometry}
          material={materials["Plant_04.002"]}
          position={[2.87, 0.26, -74.86]}
          rotation={[1.48, -0.05, -0.28]}
          scale={[7.36, 7.36, 6.84]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/sunyena.gltf");
