/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Ting(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/ting.gltf");
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera001" position={[0, 0, -0.16]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh
          name="Cylinder010"
          geometry={nodes.Cylinder010.geometry}
          material={materials["09 - Default22"]}
          position={[-3.85, 1.07, -28.03]}
          rotation={[3.05, -0.88, 1.74]}
          scale={0}
        />
        <mesh
          name="Line001"
          geometry={nodes.Line001.geometry}
          material={materials["11 - Default"]}
          position={[-3.5, 2.67, -28.17]}
          rotation={[3.05, -0.88, 1.74]}
          scale={0}
        />
        <mesh
          name="Rectangle001"
          geometry={nodes.Rectangle001.geometry}
          material={materials["09 - Default1"]}
          position={[-4.05, 3.2, -28.65]}
          rotation={[2.83, 0.68, 0.13]}
          scale={0}
        />
        <mesh
          name="Rectangle002"
          geometry={nodes.Rectangle002.geometry}
          material={materials["09 - Default1"]}
          position={[-3.45, 3.24, -28.16]}
          rotation={[2.83, 0.68, -3.03]}
          scale={0}
        />
        <mesh
          name="Rectangle003"
          geometry={nodes.Rectangle003.geometry}
          material={materials["09 - Default1"]}
          position={[-3.71, 3.58, -28.49]}
          rotation={[2.83, 0.68, 1.68]}
          scale={0}
        />
        <mesh
          name="Rectangle004"
          geometry={nodes.Rectangle004.geometry}
          material={materials["09 - Default1"]}
          position={[-3.78, 2.83, -28.31]}
          rotation={[2.83, 0.68, -1.48]}
          scale={0}
        />
        <mesh
          name="Cylinder013001"
          geometry={nodes.Cylinder013001.geometry}
          material={materials["09 - Default1"]}
          position={[7.19, -7.8, -48.34]}
          rotation={[3.13, -0.82, 1.91]}
          scale={0.01}
        />
        <mesh
          name="Cylinder014001"
          geometry={nodes.Cylinder014001.geometry}
          material={materials["09 - Default"]}
          position={[-1.66, 2.43, -59.49]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          name="Line005001"
          geometry={nodes.Line005001.geometry}
          material={materials["11 - Default"]}
          position={[8.52, -3.95, -48.79]}
          rotation={[3.13, -0.82, 1.91]}
          scale={0.01}
        />
        <mesh
          name="Line006001"
          geometry={nodes.Line006001.geometry}
          material={materials["11 - Default"]}
          position={[1.87, 2.55, -58.87]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          name="Galaxy_Book2_360_Screen"
          geometry={nodes.Galaxy_Book2_360_Screen.geometry}
          material={materials["Material.001"]}
          position={[-0.69, 0.26, -21.97]}
          rotation={[-1.7, 0.02, 0.07]}
          scale={4.07}
        />
        <mesh
          name="Cylinder013002"
          geometry={nodes.Cylinder013002.geometry}
          material={materials["09 - Default1"]}
          position={[-1.07, -5.82, -40.9]}
          rotation={[-1.68, -0.7, 2.6]}
          scale={0}
        />
        <mesh
          name="Line005002"
          geometry={nodes.Line005002.geometry}
          material={materials["11 - Default"]}
          position={[0.8, -4.68, -39.68]}
          rotation={[-1.68, -0.7, 2.6]}
          scale={0}
        />
        <mesh
          name="Galaxy_Book2"
          geometry={nodes.Galaxy_Book2.geometry}
          material={materials["Galaxy Book2 Pro 360 Screen graphite"]}
          position={[-1.01, -0.83, -18.96]}
          rotation={[0, 0.01, 0]}
          scale={7.29}
        />
        <mesh
          name="Galaxy_Book2_360"
          geometry={nodes.Galaxy_Book2_360.geometry}
          material={materials["Galaxy Book2 Pro 360 graphite"]}
          position={[-1, -1.07, -18.25]}
          rotation={[0, 0.01, 0]}
          scale={7.29}
        />
        <mesh
          name="Galaxy_Book2_360_Pen"
          geometry={nodes.Galaxy_Book2_360_Pen.geometry}
          material={materials["Galaxy Book2 Pro 360 Screen graphite"]}
          position={[-1.04, 0.46, -19.15]}
          rotation={[0, 0.01, 0]}
          scale={7.29}
        />
        <mesh
          name="Galaxy_Book2_360_Screen001"
          geometry={nodes.Galaxy_Book2_360_Screen001.geometry}
          material={materials["Material.001"]}
          position={[-1, -0.8, -18.96]}
          rotation={[-1.69, 0, 0.01]}
          scale={7.29}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ting.gltf");
